### ISSUE TITLE
FAILURE: Build failed with an exception

### ISSUE THREAD

**Issue by monk1337** [salesforce/TransmogrifAI#108]
After that i want to try one of classificiation model which is here:

https://docs.transmogrif.ai/en/stable/examples/Titanic-Binary-Classification.html

But during running command :

cd helloworld
./gradlew compileTestScala installDist
./gradlew -q sparkSubmit -Dmain=com.salesforce.hw.OpTitanicSimple -Dargs="\
`pwd`/src/main/resources/TitanicDataset/TitanicPassengersTrainData.csv"
I am getting this error:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sparkSubmit'.
> A problem occurred starting process 'command 'null/bin/spark-submit''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
I tried to find out but couldn't get any idea about this , How can i solve this issue ?

**Comment by aCampello** [comment]
Why was this issue closed? What was the solution?

**Comment by tovbinm** [comment]
presumably @monk1337 was found a problem with his environment and was able to solve it by setting up spark correctly - https://docs.transmogrif.ai/en/stable/installation/index.html
@aCampello are you experiencing the same problem?

**Comment by aCampello** [comment]
Yeah, the same "What went wrong", although it is hard to know whether the trace is the same/what is the fix. My trace is:

```
Exception in thread "main" java.lang.IllegalArgumentException: All stages must be serializable. Failed stages: TextTokenizer_000000000016,OPCollectionHashingVectorizer_000000000017,OpSetVectorizer_000000000014,RealVectorizer_000000000015,VectorsCombiner_000000000019,IntegralVectorizer_000000000013,OpSetVectorizer_00000000000f,VectorsCombiner_00000000001a,SanityChecker_00000000001b
        at com.salesforce.op.OpWorkflow$$anonfun$checkSerializable$1.apply$mcV$sp(OpWorkflow.scala:257)
        at com.salesforce.op.OpWorkflow$$anonfun$checkSerializable$1.apply(OpWorkflow.scala:254)
        at com.salesforce.op.OpWorkflow$$anonfun$checkSerializable$1.apply(OpWorkflow.scala:254)
        at scala.util.Try$.apply(Try.scala:192)
        at com.salesforce.op.OpWorkflow.checkSerializable(OpWorkflow.scala:254)
        at com.salesforce.op.OpWorkflow$$anonfun$19.apply(OpWorkflow.scala:308)
        at com.salesforce.op.OpWorkflow$$anonfun$19.apply(OpWorkflow.scala:307)
        at scala.util.Success.flatMap(Try.scala:231)
        at com.salesforce.op.OpWorkflow.validateStages(OpWorkflow.scala:307)
        at com.salesforce.op.OpWorkflow.setResultFeatures(OpWorkflow.scala:90)
        at com.salesforce.hw.OpTitanicSimple$.main(OpTitanicSimple.scala:162)
        at com.salesforce.hw.OpTitanicSimple.main(OpTitanicSimple.scala)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:775)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.IllegalArgumentException
        at org.apache.xbean.asm5.ClassReader.<init>(Unknown Source)
        at org.apache.xbean.asm5.ClassReader.<init>(Unknown Source)
        at org.apache.xbean.asm5.ClassReader.<init>(Unknown Source)
        at org.apache.spark.util.ClosureCleaner$.getClassReader(ClosureCleaner.scala:46)
        at org.apache.spark.util.FieldAccessFinder$$anon$3$$anonfun$visitMethodInsn$2.apply(ClosureCleaner.scala:443)
        at org.apache.spark.util.FieldAccessFinder$$anon$3$$anonfun$visitMethodInsn$2.apply(ClosureCleaner.scala:426)
        at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
        at scala.collection.mutable.HashMap$$anon$1$$anonfun$foreach$2.apply(HashMap.scala:103)
        at scala.collection.mutable.HashMap$$anon$1$$anonfun$foreach$2.apply(HashMap.scala:103)
        at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:230)
        at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
        at scala.collection.mutable.HashMap$$anon$1.foreach(HashMap.scala:103)
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
        at org.apache.spark.util.FieldAccessFinder$$anon$3.visitMethodInsn(ClosureCleaner.scala:426)
        at org.apache.xbean.asm5.ClassReader.a(Unknown Source)
        at org.apache.xbean.asm5.ClassReader.b(Unknown Source)
        at org.apache.xbean.asm5.ClassReader.accept(Unknown Source)
        at org.apache.xbean.asm5.ClassReader.accept(Unknown Source)
        at org.apache.spark.util.ClosureCleaner$$anonfun$org$apache$spark$util$ClosureCleaner$$clean$14.apply(ClosureCleaner.scala:257)
        at org.apache.spark.util.ClosureCleaner$$anonfun$org$apache$spark$util$ClosureCleaner$$clean$14.apply(ClosureCleaner.scala:256)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at org.apache.spark.util.ClosureCleaner$.org$apache$spark$util$ClosureCleaner$$clean(ClosureCleaner.scala:256)
        at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:156)
        at org.apache.spark.util.ClosureUtils$$anonfun$checkSerializable$1.apply(ClosureUtils.scala:44)
        at org.apache.spark.util.ClosureUtils$$anonfun$checkSerializable$1.apply(ClosureUtils.scala:44)
        at scala.util.Try$.apply(Try.scala:192)
        at org.apache.spark.util.ClosureUtils$.checkSerializable(ClosureUtils.scala:43)
        at com.salesforce.op.stages.base.unary.OpTransformer1$class.checkSerializable(UnaryTransformer.scala:67)
        at com.salesforce.op.stages.base.unary.UnaryTransformer.checkSerializable(UnaryTransformer.scala:104)
        at com.salesforce.op.OpWorkflow$$anonfun$checkSerializable$1$$anonfun$17.apply(OpWorkflow.scala:255)
        at com.salesforce.op.OpWorkflow$$anonfun$checkSerializable$1$$anonfun$17.apply(OpWorkflow.scala:255)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
        at com.salesforce.op.OpWorkflow$$anonfun$checkSerializable$1.apply$mcV$sp(OpWorkflow.scala:255)
        ... 20 more

```

**Comment by tovbinm** [comment]
Oh, this exception is way more interesting and unexpected. For some reason none of the stages in your workflow are serializable (this is a requirement for running on Spark). I have suspicion that this is something to do with the setup of your environment. Which java version do you have? You can test it by running: java -version.

**Comment by aCampello** [comment]
Oh yeah, forgot to put the specs:

```
Java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)

```

**Comment by aCampello** [comment]
Oh, ok, if I make my java se point to 1.8 by doing ```export JAVA_HOME=`/usr/libexec/java_home -v 1.8` ``` it actually works. Something to bear in mind in the installation instructions though.

**Comment by lei6315** [comment]
I have same problem
command
```
./gradlew  -q sparkSubmit -Dmain=com.salesforce.hw.OpTitanicSimple -Dargs="\
`pwd`/src/main/resources/TitanicDataset/TitanicPassengersTrainData.csv" --info
```

log
```
Initialized native services in: /Users/gaolei7/.gradle/native
The client will now receive all logging from the daemon (pid: 79174). The daemon log file: /Users/gaolei7/.gradle/daemon/5.2/daemon-79174.out.log
Starting 6th build in daemon [uptime: 1 hrs 44 mins 40.77 secs, performance: 99%, no major garbage collections]
Using 4 worker leases.
Starting Build
Settings evaluated using settings file '/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/settings.gradle'.
Projects loaded. Root project using build file '/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build.gradle'.
Included projects: [root project 'transmogrifai-helloworld']

> Configure project :
Evaluating root project 'transmogrifai-helloworld' using build file '/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build.gradle'.
All projects evaluated.
Selected primary task 'sparkSubmit' from project :
file or directory '/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/src/test/scala', not found
Tasks to be executed: [task ':generateAvroProtocol', task ':generateAvroJava', task ':compileJava', task ':scalaStyle', task ':compileScala', task ':processResources', task ':classes', task ':jar', task ':startScripts', task ':installDist', task ':copyLog4jToSpark', task ':sparkSubmit']
:generateAvroProtocol (Thread[Execution worker for ':',5,main]) started.

> Task :generateAvroProtocol NO-SOURCE
Skipping task ':generateAvroProtocol' as it has no source files and no previous output files.
:generateAvroProtocol (Thread[Execution worker for ':',5,main]) completed. Took 0.002 secs.
:generateAvroJava (Thread[Execution worker for ':',5,main]) started.

> Task :generateAvroJava
Task ':generateAvroJava' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Found 2 files
Processed src/main/avro/Passenger.avsc
Processed src/main/avro/Iris.avsc
:generateAvroJava (Thread[Execution worker for ':',5,main]) completed. Took 0.021 secs.
:compileJava (Thread[Execution worker for ':',5,main]) started.

> Task :compileJava UP-TO-DATE
file or directory '/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/src/main/java', not found
Skipping task ':compileJava' as it is up-to-date.
:compileJava (Thread[Execution worker for ':',5,main]) completed. Took 0.08 secs.
:scalaStyle (Thread[Execution worker for ':',5,main]) started.

> Task :scalaStyle UP-TO-DATE
file or directory '/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/src/test/scala', not found
Skipping task ':scalaStyle' as it is up-to-date.
:scalaStyle (Thread[Execution worker for ':',5,main]) completed. Took 0.002 secs.
:compileScala (Thread[Execution worker for ':',5,main]) started.

> Task :compileScala UP-TO-DATE
Skipping task ':compileScala' as it is up-to-date.
:compileScala (Thread[Execution worker for ':',5,main]) completed. Took 0.014 secs.
:processResources (Thread[Execution worker for ':',5,main]) started.

> Task :processResources UP-TO-DATE
Skipping task ':processResources' as it is up-to-date.
:processResources (Thread[Execution worker for ':',5,main]) completed. Took 0.003 secs.
:classes (Thread[Execution worker for ':',5,main]) started.

> Task :classes UP-TO-DATE
Skipping task ':classes' as it has no actions.
:classes (Thread[Execution worker for ':',5,main]) completed. Took 0.0 secs.
:jar (Thread[Execution worker for ':',5,main]) started.

> Task :jar UP-TO-DATE
Skipping task ':jar' as it is up-to-date.
:jar (Thread[Execution worker for ':',5,main]) completed. Took 0.001 secs.
:startScripts (Thread[Execution worker for ':',5,main]) started.

> Task :startScripts UP-TO-DATE
Skipping task ':startScripts' as it is up-to-date.
:startScripts (Thread[Execution worker for ':',5,main]) completed. Took 0.006 secs.
:installDist (Thread[Execution worker for ':' Thread 2,5,main]) started.

> Task :installDist UP-TO-DATE
Skipping task ':installDist' as it is up-to-date.
:installDist (Thread[Execution worker for ':' Thread 2,5,main]) completed. Took 0.007 secs.
:copyLog4jToSpark (Thread[Execution worker for ':' Thread 2,5,main]) started.

> Task :copyLog4jToSpark UP-TO-DATE
Skipping task ':copyLog4jToSpark' as it is up-to-date.
:copyLog4jToSpark (Thread[Execution worker for ':' Thread 2,5,main]) completed. Took 0.0 secs.
:sparkSubmit (Thread[Execution worker for ':' Thread 2,5,main]) started.

> Task :sparkSubmit FAILED
Task ':sparkSubmit' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Starting process 'command 'null/bin/spark-submit''. Working directory: /Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/null Command: null/bin/spark-submit -v --master local[*] --deploy-mode client --conf spark.serializer=org.apache.spark.serializer.KryoSerializer --driver-cores 1 --driver-memory 4G --executor-memory 2G --class com.salesforce.hw.OpTitanicSimple --name transmogrifai-helloworld:com.salesforce.hw.OpTitanicSimple --jars /Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/chill_2.11-0.8.4.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/commons-logging-1.2.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/config-1.2.1.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/minlog-1.3.0.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/tika-core-1.16.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/prefixmapper-2.82.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/jackson-dataformat-yaml-2.7.3.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/akka-actor_2.11-2.3.11.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/annotations-12.0.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/scala-xml_2.11-1.0.5.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/scala-library-2.11.12.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/joda-convert-1.8.1.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/scala-parser-combinators_2.11-1.0.4.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/jsonic-1.2.11.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/carrier-1.72.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/slf4j-api-1.7.6.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/transmogrifai-readers_2.11-0.5.1.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/sourcecode_2.11-0.1.3.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/objenesis-2.1.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/lucene-core-7.3.0.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/commons-validator-1.6.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/bijection-core_2.11-0.9.4.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/libphonenumber-8.8.5.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/geocoder-2.82.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/kryo-shaded-3.0.3.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/JavaEWAH-1.1.4.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/chill-bijection_2.11-0.8.4.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/lucene-analyzers-opennlp-7.3.0.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/opennlp-maxent-3.0.3.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/lucene-suggest-7.3.0.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/json4s-ext_2.11-3.2.11.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/snakeyaml-1.15.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/commons-io-2.6.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/enumeratum-macros_2.11-1.4.12.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/guava-14.0.1.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/scopt_2.11-3.5.0.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/algebra_2.11-0.7.0.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/commons-collections-3.2.2.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/lucene-spatial3d-7.3.0.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/lucene-analyzers-kuromoji-7.3.0.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/graph-core_2.11-1.12.5.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/transmogrifai-helloworld-0.0.1.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/enumeratum_2.11-1.4.12.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/chill-avro_2.11-0.8.4.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/lucene-analyzers-common-7.3.0.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/scala-compiler-2.11.12.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/xgboost4j-0.81.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/xgboost4j-spark-0.81.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/transmogrifai-utils_2.11-0.5.1.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/joda-time-2.9.4.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/scalaj-collection_2.11-0.1.2.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/bijection-avro_2.11-0.9.4.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/language-detector-0.0.1.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/cats-kernel_2.11-0.9.0.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/commons-beanutils-1.9.2.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/algebird-core_2.11-0.13.4.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/scala-reflect-2.11.12.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/spark-avro_2.11-4.0.0.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/transmogrifai-features_2.11-0.5.1.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/transmogrifai-core_2.11-0.5.1.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/chill-algebird_2.11-0.8.4.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/opennlp-tools-1.8.3.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/commons-digester-1.8.1.jar,/Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/chill-java-0.8.4.jar /Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/build/install/transmogrifai-helloworld/lib/transmogrifai-helloworld-0.0.1.jar /Users/gaolei7/IdeaProjects/TransmogrifAI/helloworld/src/main/resources/TitanicDataset/TitanicPassengersTrainData.csv
:sparkSubmit (Thread[Execution worker for ':' Thread 2,5,main]) completed. Took 0.006 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sparkSubmit'.
> A problem occurred starting process 'command 'null/bin/spark-submit''

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
10 actionable tasks: 2 executed, 8 up-to-date
```
I had set JAVA_HOME, how to solve this problem.

**Comment by tovbinm** [comment]
Please download Spark 2.3, extract it and set SPARK_HOME correctly (As explained here - https://docs.transmogrif.ai/en/stable/installation/index.html)

**Comment by lei6315** [comment]
I had set SPARK_HOME but still had the error.
