### ISSUE TITLE
Built failed when running TitanicDataset! But my JAVA version is right

### ISSUE THREAD

**Issue by AdrianTianyi** [salesforce/TransmogrifAI#123]
I failed when running the TitanicDataset with the command:
```bash
./gradlew -q sparkSubmit -Dmain=com.salesforce.hw.OpTitanicSimple -Dargs="\
`pwd`/src/main/resources/TitanicDataset/TitanicPassengersTrainData.csv"
```

 My JAVA version is already 1.8. And I install the package completely the same as the Installation document. But the procedure returns:
``` 
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sparkSubmit'.
> A problem occurred starting process 'command 'C:\spark-2.2.2-bin-hadoop2.7/bin/spark-submit''

The message is:

 Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':sparkSubmit'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.process.internal.ExecException: A problem occurred starting process 'command 'C:\spark-2.2.2-bin-hadoop2.7/bin/spark-submit''
        at org.gradle.process.internal.DefaultExecHandle.execExceptionFor(DefaultExecHandle.java:231)
        at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:209)
        at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandle.java:355)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:85)
        at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
        ... 3 more
Caused by: net.rubygrapefruit.platform.NativeException: Could not start 'C:\spark-2.2.2-bin-hadoop2.7/bin/spark-submit'
        at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
        at net.rubygrapefruit.platform.internal.WindowsProcessLauncher.start(WindowsProcessLauncher.java:22)
        at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:67)
        ... 4 more
Caused by: java.io.IOException: Cannot run program "C:\spark-2.2.2-bin-hadoop2.7/bin/spark-submit" (in directory "C:\spark-2.2.2-bin-hadoop2.7"): CreateProcess error=193, %1 is not a valid Win32 application
        at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
        ... 7 more
Caused by: java.io.IOException: CreateProcess error=193, %1 is not a valid Win32 application
        ... 8 more
```
I wonder what goes wrong? Thanks!

**Comment by tovbinm** [comment]
It seems that you are trying to run Spark on Windows, but the spark-submit command assumes unix/linux operating system because the way it constructs the path `C:\spark-2.2.2-bin-hadoop2.7/bin/spark-submit`.
You can try to modify the `TransmogrifAI/gradle/spark.gradle` to construct the path correctly: `def command = ["$sparkHome/bin/spark-submit"]`. In general, I think we should be able to fix this, but I wont have a way to verify it, cause I dont have a windows machine.

**Comment by tovbinm** [comment]
@AdrianTianyi did you try it out?

**Comment by AdrianTianyi** [comment]
Thanks. I have changed the routes but the problem still exists where it just shows spark-submit routine failed. It seems that the problem is because I use windows not Linux. So I am now trying virtual machine to use Linux.

**Comment by tovbinm** [comment]
You can try running on spark without using our gradle script - https://github.com/salesforce/TransmogrifAI/tree/master/helloworld#titanic-model---run-with-spark-submit

**Comment by AdrianTianyi** [comment]
Oh，thanks！But I still get sonething confusing. In fact，the place I fail is on the calling of spark-submit. Thus it seems that I need to use sparkSubmit （if I continue to use windows）？
And I want to ask another problem. Someone tells me that if I want to.use Spark，I need to install Hadoop first. Is that true？ Furthermore，after I install Spark，is it enough to only configurate the environment variable？Just like the document says export 
SPARK-HOME= .....？ I use Spark for tge first time and I wonder whether my problem arises from it？

PS：These days I am busy attending a contest，thus I am sorry that I have not catched up very much on this project. Thanks very much for your care and attention！

**Comment by tovbinm** [comment]
There are multiple good tips on how to setup Spark locally on a Windows machine - https://stackoverflow.com/a/38735202
And yes, of course you can just try to run your experiments in a virtual machine - http://www.datumly.com/2017/08/apache-spark-2-2-in-a-virtual-machine-simple-getting-started-guide-to-run-spark-on-your-laptop/

Another option to consider is to clone the TransmogrifAI, then open and then open it from an IDE such as Intellij or Eclipse. You can setup your code as unit test and run it. Here is an example is a workflow running from a test:
```scala
@RunWith(classOf[JUnitRunner])
class MyAppTest extends FlatSpec with TestSparkContext {
   "MyApp" should "train a model" in {
        // write your code here
    }
}
```

**Comment by p-kudrin** [comment]
May be it will be helpful for other windows users. I had the same issue and fixed it by modifying 'TransmogrifAI/gradle/spark.gradle'. I changed `def command = ["$sparkHome/bin/spark-submit"] ` to `def command = ["$sparkHome/bin/spark-submit.cmd"]`

**Comment by luisferreira97** [comment]
> May be it will be helpful for other windows users. I had the same issue and fixed it by modifying '/gradle/spark.gradle'. I changed `def command = ["$sparkHome/bin/spark-submit"] ` to `def command = ["$sparkHome/bin/spark-submit.cmd"]`

Did you only add the ".cmd" extension? I tried that but I still have the same error: "A problem occurred starting process 'command 'D:\Spark\spark-2.3.2-bin-hadoop2.7/bin/spark-submit''"

**Comment by luisferreira97** [comment]
> You are right, I did some other changes. First of all, I guess, you get error because of too long windows command. spark.gradle adds all jar-libraries one by one into command line, but windows has limit in 256 symbols. You have to use wildcard for classPath:
> `def classPath = "$project.projectDir.path/build/install/$project.name/lib/*"`

I did replace the "def classPath = buildFolder.filter { it.isFile() }.files.path.join(',')" by your "def classPath = "$project.projectDir.path/build/install/$project.name/lib/*" and I still got the same error. Maybe I didn't quite understand what you were trying to explain.

> But may be easer way don't use gradle task and start spark yourself from command line. Somthing like this:
> `YOUR_SPARK_HOME\bin\spark-submit.cmd --class com.salesforce.hw.OpTitanicSimple build/libs/transmogrifai-helloworld-0.0.1-all.jar src/main/resources/TitanicDataset/TitanicPassengersTrainData.csv`

I tried that and it worked, thanks a lot! 👍
