### ISSUE TITLE
Caused by: java.lang.NullPointerException: Null value appeared in non-nullable field:

### ISSUE THREAD

**Issue by monk1337** [salesforce/TransmogrifAI#124]
I am trying to work with one binary classification example same as titanic problem demo, But i am getting Null value error , I have already checked the csv file there are no null values but still it is showing null values.
My data looks [like this ](https://github.com/monk1337/TransmogrifAI-Auto-ml/blob/master/data_reads.csv) main file code is:

```scala
/*
 * Copyright (c) 2017, Salesforce.com, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * 3. Neither the name of Salesforce.com nor the names of its contributors may
 * be used to endorse or promote products derived from this software without
 * specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

package com.salesforce.hw

import com.salesforce.op._
import com.salesforce.op.evaluators.Evaluators
import com.salesforce.op.features.FeatureBuilder
import com.salesforce.op.features.types._
import com.salesforce.op.readers.DataReaders
import com.salesforce.op.stages.impl.classification.BinaryClassificationModelSelector
import com.salesforce.op.stages.impl.classification.ClassificationModelsToTry._
import org.apache.spark.SparkConf
import org.apache.spark.sql.SparkSession

/**
 * Define a case class corresponding to our data file (nullable columns must be Option types)
 *
 * @param id       passenger id
 * @param survived 1: survived, 0: did not survive
 * @param pClass   passenger class
 * @param name     passenger name
 * @param sex      passenger sex (male/female)
 * @param age      passenger age (one person has a non-integer age so this must be a double)
 * @param sibSp    number of siblings/spouses traveling with this passenger
 * @param parCh    number of parents/children traveling with this passenger
 * @param ticket   ticket id string
 * @param fare     ticket price
 * @param cabin    cabin id string
 * @param embarked location where passenger embarked
 */
case class Passenger
(
  id: Option[Int],
  blue_ca_1: Option[Int],
  blue_ca_2: Option[Int],
  blue_ca_3: Option[Int],
  blue_ca_4: Option[Int],
  blue_ca_5: Option[Int],
  blue_ca_6: Option[Int],
  blue_ca_7: Option[Int],
  blue_ca_8: Option[Int],
  blue_ca_9: Option[Int],
  blue_ca_10: Option[Int],
  blue_ca_11: Option[Int],
  blue_ca_12: Option[Int],
  blue_ca_13: Option[Int],
  blue_ca_14: Option[Int],
  blue_ca_15: Option[Int],
  blue_ca_16: Option[Int],
  blue_ca_17: Option[Int],
  outcome: Int
)

/**
 * A simplified TransmogrifAI example classification app using the Titanic dataset
 */
object OpTitanicSimple {

  /**
   * Run this from the command line with
   * ./gradlew sparkSubmit -Dmain=com.salesforce.hw.OpTitanicSimple -Dargs=/full/path/to/csv/file
   */
  def main(args: Array[String]): Unit = {
    if (args.isEmpty) {
      println("You need to pass in the CSV file path as an argument")
      sys.exit(1)
    }
    val csvFilePath = args(0)
    println(s"Using user-supplied CSV file path: $csvFilePath")

    // Set up a SparkSession as normal
    val conf = new SparkConf().setAppName(this.getClass.getSimpleName.stripSuffix("$"))
    implicit val spark = SparkSession.builder.config(conf).getOrCreate()

    ////////////////////////////////////////////////////////////////////////////////
    // RAW FEATURE DEFINITIONS
    /////////////////////////////////////////////////////////////////////////////////

    // Define features using the OP types based on the data
    val blue_ca_1 = FeatureBuilder.Integral[Passenger].extract(_.blue_ca_1.toIntegral).asPredictor
    val blue_ca_2 = FeatureBuilder.Integral[Passenger].extract(_.blue_ca_2.toIntegral).asPredictor
    val blue_ca_3 = FeatureBuilder.Integral[Passenger].extract(_.blue_ca_3.toIntegral).asPredictor
    val blue_ca_4 = FeatureBuilder.Integral[Passenger].extract(_.blue_ca_4.toIntegral).asPredictor
    val blue_ca_5 = FeatureBuilder.Integral[Passenger].extract(_.blue_ca_5.toIntegral).asPredictor
    val blue_ca_6 = FeatureBuilder.Integral[Passenger].extract(_.blue_ca_6.toIntegral).asPredictor
    val blue_ca_7 = FeatureBuilder.Integral[Passenger].extract(_.blue_ca_7.toIntegral).asPredictor
    val blue_ca_8 = FeatureBuilder.Integral[Passenger].extract(_.blue_ca_8.toIntegral).asPredictor
    val blue_ca_9 = FeatureBuilder.Integral[Passenger].extract(_.blue_ca_9.toIntegral).asPredictor
    val blue_ca_10 = FeatureBuilder.Integral[Passenger].extract(_.blue_ca_10.toIntegral).asPredictor
    val blue_ca_11 = FeatureBuilder.Integral[Passenger].extract(_.blue_ca_11.toIntegral).asPredictor
    val blue_ca_12 = FeatureBuilder.Integral[Passenger].extract(_.blue_ca_12.toIntegral).asPredictor
    val blue_ca_13 = FeatureBuilder.Integral[Passenger].extract(_.blue_ca_13.toIntegral).asPredictor
    val blue_ca_14 = FeatureBuilder.Integral[Passenger].extract(_.blue_ca_14.toIntegral).asPredictor
    val blue_ca_15 = FeatureBuilder.Integral[Passenger].extract(_.blue_ca_15.toIntegral).asPredictor
    val blue_ca_16 = FeatureBuilder.Integral[Passenger].extract(_.blue_ca_16.toIntegral).asPredictor
    val blue_ca_17 = FeatureBuilder.Integral[Passenger].extract(_.blue_ca_17.toIntegral).asPredictor
    val outcome = FeatureBuilder.RealNN[Passenger].extract(_.outcome.toRealNN).asResponse

    ////////////////////////////////////////////////////////////////////////////////
    // TRANSFORMED FEATURES
    /////////////////////////////////////////////////////////////////////////////////

    // Do some basic feature engineering using knowledge of the underlying dataset

    // Define a feature of type vector containing all the predictors you'd like to use
    val passengerFeatures = Seq(
      blue_ca_1, blue_ca_2, blue_ca_3, blue_ca_4, blue_ca_5, blue_ca_6,
      blue_ca_7, blue_ca_8, blue_ca_9, blue_ca_10, blue_ca_11,
      blue_ca_12, blue_ca_13, blue_ca_14, blue_ca_15, blue_ca_16, blue_ca_17
    ).transmogrify()

    // Optionally check the features with a sanity checker
    val sanityCheck = true
    val finalFeatures = if (sanityCheck) outcome.sanityCheck(passengerFeatures) else passengerFeatures

    // Define the model we want to use (here a simple logistic regression) and get the resulting output
    val (prediction, rawPrediction, prob) =
      BinaryClassificationModelSelector.withTrainValidationSplit()
        .setModelsToTry(LogisticRegression)
        .setInput(outcome, finalFeatures).getOutput()

    val evaluator = Evaluators.BinaryClassification()
      .setLabelCol(outcome)
      .setRawPredictionCol(rawPrediction)
      .setPredictionCol(prediction)
      .setProbabilityCol(prob)

    ////////////////////////////////////////////////////////////////////////////////
    // WORKFLOW
    /////////////////////////////////////////////////////////////////////////////////

    import spark.implicits._ // Needed for Encoders for the Passenger case class
    // Define a way to read data into our Passenger class from our CSV file
    val trainDataReader = DataReaders.Simple.csvCase[Passenger](
      path = Option(csvFilePath),
      key = _.id.toString
    )

    // Define a new workflow and attach our data reader
    val workflow =
      new OpWorkflow()
        .setResultFeatures(outcome, rawPrediction, prob, prediction)
        .setReader(trainDataReader)

    // Fit the workflow to the data
    val fittedWorkflow = workflow.train()
    println(s"Summary: ${fittedWorkflow.summary()}")

    // Manifest the result features of the workflow
    println("Scoring the model")
    val (dataframe, metrics) = fittedWorkflow.scoreAndEvaluate(evaluator = evaluator)

    println("Transformed dataframe columns:")
    dataframe.columns.foreach(println)
    println("Metrics:")
    println(metrics)
  }
}
```

And Passenger file ( variables definition file ) looks like this:

```
{
  "type" : "record",
  "name" : "Passenger",
  "namespace" : "com.salesforce.hw.tpo",
  "fields" : [ {
    "name" : "blue_ca_1",
    "type" : [ "double", "null" ]
  }, {
    "name" : "blue_ca_2",
    "type" : [ "double", "null" ],
    "default": 0
  }, {
    "name" : "blue_ca_3",
    "type" : [ "double", "null" ]
  }, {
    "name" : "blue_ca_4",
    "type" : [ "double", "null" ]
  }, {
    "name" : "blue_ca_5",
    "type" : [ "double", "null" ]
  }, {
    "name" : "blue_ca_6",
    "type" : [ "double", "null" ]
  }, {
    "name" : "blue_ca_7",
    "type" : [ "double", "null" ]
  }, {
    "name" : "blue_ca_8",
    "type" : [ "double", "null" ]
  }, {
    "name" : "blue_ca_9",
    "type" : [ "double", "null" ]
  }, {
    "name" : "blue_ca_10",
    "type" : [ "double", "null" ]
  }, {
    "name" : "blue_ca_11",
    "type" : [ "int", "null" ]
  }, {
    "name" : "blue_ca_12",
    "type" : [ "int", "null" ]
  }, {
    "name" : "blue_ca_13",
    "type" : [ "int", "null" ]
  }, {
    "name" : "blue_ca_14",
    "type" : [ "int", "null" ]
  }, {
    "name" : "blue_ca_15",
    "type" : [ "int", "null" ]
  }, {
    "name" : "blue_ca_16",
    "type" : [ "int", "null" ]
  }, {
    "name" : "blue_ca_17",
    "type" : [ "int", "null" ]
  }, {
    "name" : "outcome",
    "type" : [ "int", "null" ]
  } ]
}

```
Here are all the files https://github.com/monk1337/TransmogrifAI-Auto-ml

I Have two questions : 

response variables should be cast in real ( float ) ? because outcome will be probability of two classes which will be float values so should i do this ? : 

    val outcome = FeatureBuilder.RealNN[Passenger].extract(_.outcome.toRealNN).asResponse

or this : 

        val outcome = FeatureBuilder.Integral[Passenger].extract(_.outcome.toIntegral).asResponse

Second thing , How to solve that Null value issue and run this successfully ?

Thanks in advance !

**Comment by monk1337** [comment]
That issue have been solved , I am running iris model on iris dataset in helloworld , But it's taking a lot of time after splitting the data , It's stuck at this line : 

```
18/09/12 17:29:25 INFO OpCrossValidation: Best set of parameters:
{
        rfc_2531cfc708bc-impurity: gini,
        rfc_2531cfc708bc-maxBins: 32,
        rfc_2531cfc708bc-maxDepth: 3,
        rfc_2531cfc708bc-minInfoGain: 0.001,
        rfc_2531cfc708bc-minInstancesPerNode: 10,
        rfc_2531cfc708bc-numTrees: 50,
        rfc_2531cfc708bc-subsamplingRate: 1.0
} for RandomForestClassifier
18/09/12 17:29:25 INFO OpCrossValidation: Best train validation split metric: 0.02941176470588236.
<===========--> 91% EXECUTING [32m 11s]
> :sparkSubmit
```


is it training or code is stuck somewhere , If it is training then how long it will take normally, and is there any option where i can set epoch , printing result after each epoch something ?

**Comment by tovbinm** [comment]
Training usually takes about 1-5 minutes depending on how fast your hardware is (32 minutes is definitely too long). You can try browsing to Spark web UI and inspect where is it stuck at http://127.0.0.1:4040

**Comment by tovbinm** [comment]
Spark web UI is only accessible during the execution of the spark job. So after you run the `./gradlew sparkSubmit` jump to your browser and try to refresh the http://127.0.0.1:4040 several times.

**Comment by ajayborra** [comment]
Perhaps you can try adding `log4j.rootLogger=INFO` instead of `log4j.logger.com.salesforce.op.utils.spark.OpSparkListener=INFO` to get a more detailed log.

**Comment by monk1337** [comment]
If i am using score or evaluate command then , I am not able to see any score or validation accuracy , It is stuck at this point : 

```
c/userFiles-876763f8-79c7-4e9f-9bb3-dbcf71f17ada/scopt_2.11-3.5.0.jar to class loader
18/09/13 13:09:51 INFO Executor: Fetching spark://monks-air:53638/jars/carrier-1.72.jar with timestamp 1536824388036
18/09/13 13:09:51 INFO Utils: Fetching spark://monks-air:53638/jars/carrier-1.72.jar to /private/var/folders/3_/q9nh4dx91kq8j618fk9p5tmw0000gn/T/spark-e89b6682-f8a1-4ce3-ac76-c4d91939ffbc/userFiles-876763f8-79c7-4e9f-9bb3-dbcf71f17ada/fetchFileTemp3717913299294748096.tmp
18/09/13 13:09:51 INFO Executor: Adding file:/private/var/folders/3_/q9nh4dx91kq8j618fk9p5tmw0000gn/T/spark-e89b6682-f8a1-4ce3-ac76-c4d91939ffbc/userFiles-876763f8-79c7-4e9f-9bb3-dbcf71f17ada/carrier-1.72.jar to class loader
18/09/13 13:09:51 INFO HadoopRDD: Input split: file:/tmp/iris-model/op-model.json/part-00000:0+55653
18/09/13 13:09:51 INFO Executor: Finished task 0.0 in stage 0.0 (TID 0). 57116 bytes result sent to driver
18/09/13 13:09:51 INFO TaskSetManager: Finished task 0.0 in stage 0.0 (TID 0) in 1516 ms on localhost (executor driver) (1/1)
18/09/13 13:09:51 INFO TaskSchedulerImpl: Removed TaskSet 0.0, whose tasks have all completed, from pool 
18/09/13 13:09:51 INFO DAGScheduler: ResultStage 0 (collect at OpWorkflowModelReader.scala:59) finished in 1.633 s
18/09/13 13:09:51 INFO OpSparkListener: APP_NAME:op-helloworld:com.salesforce.hw.iris.OpIris,RUN_TYPE:Evaluate,APP:op-helloworld:com.salesforce.hw.iris.OpIris,APP_ID:local-1536824388139,JOB_ID:0,RESULT:JobSucceeded,JOB_TIME_MS:1690
18/09/13 13:09:51 INFO DAGScheduler: Job 0 finished: collect at OpWorkflowModelReader.scala:59, took 1.718626 s
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.spark.ml.util.DefaultParamsReader$.getAndSetParams(Lorg/apache/spark/ml/param/Params;Lorg/apache/spark/ml/util/DefaultParamsReader$Metadata;)V
        at org.apache.spark.ml.SparkDefaultParamsReadWrite$.getAndSetParams(SparkDefaultParamsReadWrite.scala:90)
        at com.salesforce.op.stages.OpPipelineStageReader.loadFromJsonString(OpPipelineStageReader.scala:97)
        at com.salesforce.op.stages.OpPipelineStageReader.loadFromJson(OpPipelineStageReader.scala:74)
        at com.salesforce.op.OpWorkflowModelReader$$anonfun$5.apply(OpWorkflowModelReader.scala:126)
        at com.salesforce.op.OpWorkflowModelReader$$anonfun$5.apply(OpWorkflowModelReader.scala:122)
        at scala.collection.immutable.List.map(List.scala:273)
        at com.salesforce.op.OpWorkflowModelReader.loadStages(OpWorkflowModelReader.scala:122)
        at com.salesforce.op.OpWorkflowModelReader.com$salesforce$op$OpWorkflowModelReader$$resolveFeaturesAndStages(OpWorkflowModelReader.scala:109)
        at com.salesforce.op.OpWorkflowModelReader$$anonfun$loadJson$3$$anonfun$apply$1$$anonfun$apply$3$$anonfun$apply$4.apply(OpWorkflowModelReader.scala:87)
        at com.salesforce.op.OpWorkflowModelReader$$anonfun$loadJson$3$$anonfun$apply$1$$anonfun$apply$3$$anonfun$apply$4.apply(OpWorkflowModelReader.scala:87)
        at scala.util.Try$.apply(Try.scala:192)
        at com.salesforce.op.OpWorkflowModelReader$$anonfun$loadJson$3$$anonfun$apply$1$$anonfun$apply$3.apply(OpWorkflowModelReader.scala:87)
        at com.salesforce.op.OpWorkflowModelReader$$anonfun$loadJson$3$$anonfun$apply$1$$anonfun$apply$3.apply(OpWorkflowModelReader.scala:86)
        at scala.util.Success.flatMap(Try.scala:231)
        at com.salesforce.op.OpWorkflowModelReader$$anonfun$loadJson$3$$anonfun$apply$1.apply(OpWorkflowModelReader.scala:86)
        at com.salesforce.op.OpWorkflowModelReader$$anonfun$loadJson$3$$anonfun$apply$1.apply(OpWorkflowModelReader.scala:85)
        at scala.util.Success.flatMap(Try.scala:231)
        at com.salesforce.op.OpWorkflowModelReader$$anonfun$loadJson$3.apply(OpWorkflowModelReader.scala:85)
        at com.salesforce.op.OpWorkflowModelReader$$anonfun$loadJson$3.apply(OpWorkflowModelReader.scala:84)
        at scala.util.Success.flatMap(Try.scala:231)
        at com.salesforce.op.OpWorkflowModelReader.loadJson(OpWorkflowModelReader.scala:84)
        at com.salesforce.op.OpWorkflowModelReader$$anonfun$loadJson$2.apply(OpWorkflowModelReader.scala:73)
        at com.salesforce.op.OpWorkflowModelReader$$anonfun$loadJson$2.apply(OpWorkflowModelReader.scala:73)
        at scala.util.Success.flatMap(Try.scala:231)
        at com.salesforce.op.OpWorkflowModelReader.loadJson(OpWorkflowModelReader.scala:73)
        at com.salesforce.op.OpWorkflowModelReader$$anonfun$2.apply(OpWorkflowModelReader.scala:60)
        at com.salesforce.op.OpWorkflowModelReader$$anonfun$2.apply(OpWorkflowModelReader.scala:60)
        at scala.util.Success.flatMap(Try.scala:231)
        at com.salesforce.op.OpWorkflowModelReader.load(OpWorkflowModelReader.scala:60)
        at com.salesforce.op.OpWorkflow.loadModel(OpWorkflow.scala:456)
        at com.salesforce.op.OpWorkflowRunner.evaluate(OpWorkflowRunner.scala:276)
        at com.salesforce.op.OpWorkflowRunner.run(OpWorkflowRunner.scala:311)
        at com.salesforce.op.OpAppWithRunner.run(OpApp.scala:211)
        at com.salesforce.op.OpApp.main(OpApp.scala:182)
        at com.salesforce.hw.iris.OpIris.main(OpIris.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:879)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:197)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:227)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:136)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
18/09/13 13:09:52 INFO SparkContext: Invoking stop() from shutdown hook
18/09/13 13:09:52 INFO OpSparkListener: APP_NAME:op-helloworld:com.salesforce.hw.iris.OpIris,RUN_TYPE:Evaluate,APP:op-helloworld:com.salesforce.hw.iris.OpIris,APP_ID:local-1536824388139,APP_TIME_MS:3079
18/09/13 13:09:52 INFO SparkUI: Stopped Spark web UI at http://monks-air:4040
18/09/13 13:09:52 INFO OpWorkflowRunner: Total run time: 3.079s
<===========--> 91% EXECUTING [1m 7s]
> :sparkSubmit 
```

**Comment by tovbinm** [comment]
@monk1337 are you sure you are using the Spark 2.2.1 version? this type of error usually indicates that.

**Comment by tovbinm** [comment]
@monk1337 I suggest to move this conversation to https://gitter.im/salesforce-TransmogrifAI-Issues/Issues

**Comment by ajayborra** [comment]
@monk1337 As @tovbinm mentioned this issues is due to spark version mismatch. Ensure that your spark version at [helloworld/build.gradle](https://github.com/salesforce/TransmogrifAI/blob/master/helloworld/build.gradle#L39) and `echo $SPARK_HOME` spark version are matching.
