### ISSUE TITLE
Non fatal URISyntaxException when running a workflow on spark-shell

### ISSUE THREAD

**Issue by sbrunk** [salesforce/TransmogrifAI#144]
**Describe the bug**
When executing a workflow interactively using spark-shell, I get a lot of URISyntaxExceptions from the Spark ExecutorClassLoader.

```
ERROR ExecutorClassLoader: Failed to check existence of class <root>.package on REPL class server at spark://192.168.178.56:56688/classes
java.net.URISyntaxException: Illegal character in path at index 37: spark://192.168.178.56:56688/classes/<root>/package.class
```

Note that the workflow still finishes correctly, so it's more an annoyance than a serious issue.

**To Reproduce**
Copy the following snippet, which is the TitanicMini example as REPL version into a file titanic-mini.sc

```scala
import com.salesforce.op._
import com.salesforce.op.features.FeatureBuilder
import com.salesforce.op.features.types._
import com.salesforce.op.readers.DataReaders
import com.salesforce.op.stages.impl.classification._
import com.salesforce.op.stages.impl.classification.BinaryClassificationModelsToTry.OpLogisticRegression
import org.apache.spark.SparkConf
import org.apache.spark.sql.SparkSession
import org.apache.log4j.{Level, LogManager}

case class Passenger(
  id: Long,
  survived: Double,
  pClass: Option[Long],
  name: Option[String],
  sex: Option[String],
  age: Option[Double],
  sibSp: Option[Long],
  parCh: Option[Long],
  ticket: Option[String],
  fare: Option[Double],
  cabin: Option[String],
  embarked: Option[String]
)

implicit val s = spark
import s.implicits._
LogManager.getLogger("com.salesforce.op").setLevel(Level.ERROR)
val passengersData = DataReaders.Simple.csvCase[Passenger](Some("TitanicPassengersTrainData.csv"), key = _.id.toString).readDataset().toDF()
val (survived, features) = FeatureBuilder.fromDataFrame[RealNN](passengersData, response = "survived")
val featureVector = features.transmogrify()
val checkedFeatures = survived.sanityCheck(featureVector, checkSample = 1.0, removeBadFeatures = true)
val prediction = BinaryClassificationModelSelector.
  withCrossValidation(modelTypesToUse = Seq(OpLogisticRegression)). 
  setInput(survived, checkedFeatures).getOutput()
val model = new OpWorkflow().setInputDataset(passengersData).setResultFeatures(prediction).train()
println(model.summaryPretty())
```

Run spark-shell and load the example:
```bash
wget https://raw.githubusercontent.com/salesforce/TransmogrifAI/master/helloworld/src/main/resources/TitanicDataset/TitanicPassengersTrainData.csv
$SPARK_HOME/bin/spark-shell --packages com.salesforce.transmogrifai:transmogrifai-core_2.11:0.4.0
...
scala> :load titanic-mini.sc
```

**Expected behavior**
Execution of the example without errors.

**Logs or screenshots**
```
...
18/09/30 11:27:45 ERROR ExecutorClassLoader: Failed to check existence of class <root>.package on REPL class server at spark://192.168.178.56:56688/classes
java.net.URISyntaxException: Illegal character in path at index 37: spark://192.168.178.56:56688/classes/<root>/package.class
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at org.apache.spark.rpc.netty.NettyRpcEnv.openChannel(NettyRpcEnv.scala:327)
	at org.apache.spark.repl.ExecutorClassLoader.org$apache$spark$repl$ExecutorClassLoader$$getClassFileInputStreamFromSparkRPC(ExecutorClassLoader.scala:90)
	at org.apache.spark.repl.ExecutorClassLoader$$anonfun$1.apply(ExecutorClassLoader.scala:57)
...
```

**Additional context**
Seen on MacOS and Linux. Only tested on a local cluster.

**Comment by tovbinm** [comment]
@sbrunk this is indeed rather annoying. I think it has to do with the Scala REPL default package name `<root>`. If there was a way to set the default package into something more meaningful than `<root>`, but I don't think Scala REPL supports changing it.

Perhaps we should open a but against Spark.

**Comment by sbrunk** [comment]
Agreed this seems to be more of a Spark issue. Perhaps it would be good to find a minimal example causing the Error, though.

**Comment by tovbinm** [comment]
@sbrunk I am going to close this one as we dont have any solution at our hands for this.
