### ISSUE TITLE
sanitychecker seems do not work for realmap featuretype

### ISSUE THREAD

**Issue by liuzhenhai93** [salesforce/TransmogrifAI#151]
**Describe the bug**
sanitychecker seems do not work for realmap featuretype

**Logs or screenshots**
```
18/10/08 10:57:58 ERROR ApplicationMaster: User class threw exception: java.lang.IllegalArgumentException: requirement failed: Vector column 99 has multiple null indicator fields: ArrayBuffer((99,({
  "parentFeatureName" : [ "delv_way_cd_count" ],
  "parentFeatureType" : [ "com.salesforce.op.features.types.RealMap" ],
  "grouping" : "99",
  "indicatorValue" : "NullIndicatorValue",
  "index" : 87,
  "nullIndicator" : true
},87)), (99,({
  "parentFeatureName" : [ "pay_mode_cd_count" ],
  "parentFeatureType" : [ "com.salesforce.op.features.types.RealMap" ],
  "grouping" : "99",
  "indicatorValue" : "NullIndicatorValue",
  "index" : 126557,
  "nullIndicator" : true
},126557)))
java.lang.IllegalArgumentException: requirement failed: Vector column 99 has multiple null indicator fields: ArrayBuffer((99,({
  "parentFeatureName" : [ "delv_way_cd_count" ],
  "parentFeatureType" : [ "com.salesforce.op.features.types.RealMap" ],
  "grouping" : "99",
  "indicatorValue" : "NullIndicatorValue",
  "index" : 87,
  "nullIndicator" : true
},87)), (99,({
  "parentFeatureName" : [ "pay_mode_cd_count" ],
  "parentFeatureType" : [ "com.salesforce.op.features.types.RealMap" ],
  "grouping" : "99",
  "indicatorValue" : "NullIndicatorValue",
  "index" : 126557,
  "nullIndicator" : true
},126557)))
	at com.salesforce.op.stages.impl.preparators.SanityChecker$$anonfun$makeColumnStatistics$2.apply(SanityChecker.scala:286)
	at com.salesforce.op.stages.impl.preparators.SanityChecker$$anonfun$makeColumnStatistics$2.apply(SanityChecker.scala:284)
	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:221)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:428)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:428)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:428)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:428)
	at com.salesforce.op.stages.impl.preparators.SanityChecker.makeColumnStatistics(SanityChecker.scala:284)
	at com.salesforce.op.stages.impl.preparators.SanityChecker.fitFn(SanityChecker.scala:652)
	at com.salesforce.op.stages.base.binary.BinaryEstimator.fit(BinaryEstimator.scala:107)
	at com.salesforce.op.stages.base.binary.BinaryEstimator.fit(BinaryEstimator.scala:61)
	at com.salesforce.op.utils.stages.FitStagesUtil$$anonfun$20.apply(FitStagesUtil.scala:265)
	at com.salesforce.op.utils.stages.FitStagesUtil$$anonfun$20.apply(FitStagesUtil.scala:264)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at com.salesforce.op.utils.stages.FitStagesUtil$.com$salesforce$op$utils$stages$FitStagesUtil$$fitAndTransformLayer(FitStagesUtil.scala:264)
	at com.salesforce.op.utils.stages.FitStagesUtil$$anonfun$17.apply(FitStagesUtil.scala:227)
	at com.salesforce.op.utils.stages.FitStagesUtil$$anonfun$17.apply(FitStagesUtil.scala:225)
	at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:57)
	at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:66)
	at scala.collection.mutable.ArrayOps$ofRef.foldLeft(ArrayOps.scala:186)
	at com.salesforce.op.utils.stages.FitStagesUtil$.fitAndTransformDAG(FitStagesUtil.scala:225)
	at com.salesforce.op.OpWorkflow.fitStages(OpWorkflow.scala:384)
	at com.salesforce.op.OpWorkflow.train(OpWorkflow.scala:335)
```

**Additional context**
as far as I am concerned,map  featuretype are for sparse features (for  most shallow ML tasks in real world.features are sparse)

**Comment by leahmcguire** [comment]
Thank you for the issue! It looks like what is happening is that you have two different maps with the same key and we failed to include the parent feature name in our null indicator statistics. I will put in a PR to fix :-)
