### ISSUE TITLE
java.lang.NoClassDefFoundError: com/fasterxml/jackson/module/scala/modifiers/EitherModule

### ISSUE THREAD

**Issue by hmcc** [salesforce/TransmogrifAI#162]
We're using TransmogrifAI in a project which also pulls in a newer version of Jackson from another dependency. When we do that, we see the exception
```
[error] Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/module/scala/modifiers/EitherModule
[error]         at java.lang.ClassLoader.defineClass1(Native Method)
[error]         at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
[error]         at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[error]         at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
[error]         at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
[error]         at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
[error]         at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
[error]         at java.security.AccessController.doPrivileged(Native Method)
[error]         at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
[error]         at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error]         at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
[error]         at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error]         at java.lang.ClassLoader.defineClass1(Native Method)
[error]         at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
[error]         at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[error]         at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
[error]         at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
[error]         at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
[error]         at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
[error]         at java.security.AccessController.doPrivileged(Native Method)
[error]         at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
[error]         at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error]         at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
[error]         at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error]         at com.salesforce.op.utils.json.JsonLike$class.toJson(JsonUtils.scala:179)
```

`EitherModule` was moved in [this commit](https://github.com/FasterXML/jackson-module-scala/commit/a3a7e5feb9b178c0c044eeb57ae30e079da05382).

**Comment by tovbinm** [comment]
You can try forcing specific jackson version in your project and see it works for you.

Spark 3.x will have jackson 2.9.6 - https://issues.apache.org/jira/browse/SPARK-24601

**Comment by hmcc** [comment]
Yes, I can force Jackson down to 2.7.3 in my project (the latest before the commit that moved `EitherModule`) and it works fine. 

You're saying TransmogrifAI can't/shouldn't go higher because that's what Spark 2.2.x/2.3.x uses?

**Comment by tovbinm** [comment]
Correct.
