### ISSUE TITLE
XGBoost error code 255

### ISSUE THREAD

**Issue by albertodema** [salesforce/TransmogrifAI#181]
Hi I am trying to use the new XGBoost support in master (latest commit d0785f0a6715ed0a02ba92072c6eb00c651e5a1a) but I am facing the following issue:
Here the code (BinaryClassification of Titanic Dataset=passengersData, targetColumn is Survived)

```scala
val (saleprice, features) = FeatureBuilder.fromDataFrame[RealNN](passengersData, response = targetColumn)
      
val featureVector = features.transmogrify()

val checkedFeatures = saleprice.sanityCheck(featureVector, removeBadFeatures = true)

val prediction = BinaryClassificationModelSelector.withCrossValidation(modelTypesToUse = Seq(
        OpXGBoostClassifier
      )).setInput(saleprice, checkedFeatures).getOutput()

val wf = new OpWorkflow()

val model = wf.setInputDataset(passengersData).setResultFeatures(passengerId, checkedFeatures,prediction).train()

val results = "Model summary:\n" + model.summaryPretty()
println(results)
```

Attached the log and the error
[logxg.txt](https://github.com/salesforce/TransmogrifAI/files/2571735/logxg.txt)

**Comment by tovbinm** [comment]
@albertodema I don't see any explicit errors emitted except the error status. I would recommend asking on https://github.com/dmlc/xgboost/issues

**Comment by albertodema** [comment]
@tovbinm  thanks for your input but they will likely to ask me how transmogrifai is calling their module , with which parameters , etc..
The error is happening on both IntelliJ IDE and in a spark cluster (standalone) on the titanic dataset, can you do test with the code and if you have the same error share with me the way XGBoost has been called so I can raise a proper request to xgboost team?
Thanks,
Alberto.

**Comment by tovbinm** [comment]
@albertodema I think it might be related this issue https://github.com/dmlc/xgboost/issues/2449, since when we do cross validation we train multiple models. But I tried setting the parallelism to 1 - and the error still happens sometimes. So my bet that there is some race condition that happens which I am not sure how to track yet. @CodingCat might have some ideas?

**Comment by CodingCat** [comment]
which version of xgb are you using?

**Comment by tovbinm** [comment]
The latest - `0.81` with Spark `2.3.2`.

**Comment by CodingCat** [comment]
Ok..we are supposed to have fixed this issue in 0.81...and I can actually run cross validation without any issue...can you provide a way to reproduce consistenly?

**Comment by albertodema** [comment]
@CodingCat  on a laptop with IntelliJ first than inside a docker container, I tried to launch spark also in single core mode but the error happens the same.

**Comment by tovbinm** [comment]
Here is how to reproduce. I train 10 xgboost models in parallel and it fails:
```scala
  val sparse = RandomVector.sparse(RandomReal.uniform[Real](), 1000).take(10000)
    val labels = RandomBinary(0.5).withProbabilityOfEmpty(0.0).take(10000).map(b => b.toDouble.toRealNN(0.0))
    val sample = sparse.zip(labels).toSeq
    val (d, feats, lbl) = TestFeatureBuilder(sample)

    val data = d.repartition(100)

    (1 to 10).par.map { _ =>
      val x = new XGBoostClassifier().setLabelCol(lbl.name).setFeaturesCol(feats.name)
      x.set(x.trackerConf, TrackerConf(0L, "scala"))
      val xm = x.fit(data)
      val xtransformed = xm.transform(data)
      xtransformed.show()
    }
```

**Comment by CodingCat** [comment]
so it only happens with parallel model training?

**Comment by zhenchuan** [comment]
Is this question still being followed up? I also encountered the same problem.

**Comment by tovbinm** [comment]
Yes, we are aware of the problem, but we were unable to track down the reason for it yet. Perhaps you want to look into it? @zhenchuan this would be a very valuable contribution :)

**Comment by timsetsfire** [comment]
Is it possible related to this https://github.com/dmlc/xgboost/issues/4054

**Comment by tovbinm** [comment]
@timsetsfire thanks. I will give it a try. Also `0.82` is out and might have some related fixes :crossed_fingers:

**Comment by tovbinm** [comment]
Here is another error of the same type https://github.com/dmlc/xgboost/issues/3418 

@CodingCat any suggestions on how to overcome it?

**Comment by CodingCat** [comment]
are you actually using scala-version of rabit?

**Comment by CodingCat** [comment]
@cq

**Comment by tovbinm** [comment]
Yes, it fails with Scala tracker (Python implementation of rabbit tracker on Databricks works great).

**Comment by CodingCat** [comment]
ah......scala tracker.....out of maintenance for a while......

**Comment by tovbinm** [comment]
Thanks @wsuchy and @CodingCat

**Comment by tovbinm** [comment]
We will update project with the upcoming 0.83 (once available). 
@albertodema for now please use `TrackerConf(0L, "python")` and follow the instructions on XGBoost project page on how to setup Python RabitTracker.

**Comment by shenzgang** [comment]
Hello, I also encountered the same problem, I use a spark - 2.3.2, xgboost4j - spark used is 0.90, and then throw model training failure (ml. DMLC. Xgboost4j. Java. XGBoostError: XGBoostModel training failed).

Container id: container_e03_1568625988058_7223_01_000004
Exit code: 255
Stack trace: ExitCodeException exitCode=255: 
	at org.apache.hadoop.util.Shell.runCommand(Shell.java:545)
	at org.apache.hadoop.util.Shell.run(Shell.java:456)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:722)
	at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:212)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2019-09-25 10:31:13 [WARN] Model OpXGBoostClassifier attempted in model selector with failed with following issue: 
com.salesforce.op.stages.impl.tuning.OpValidator$$anonfun$9$$anonfun$10$$anonfun$apply$1.applyOrElse(OpValidator.scala:326)
org.apache.spark.SparkException: Job 45 cancelled because SparkContext was shut down
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$cleanUpAfterSchedulerStop$1.apply(DAGScheduler.scala:837)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$cleanUpAfterSchedulerStop$1.apply(DAGScheduler.scala:835)
	at scala.collection.mutable.HashSet.foreach(HashSet.scala:78)
	at org.apache.spark.scheduler.DAGScheduler.cleanUpAfterSchedulerStop(DAGScheduler.scala:835)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onStop(DAGScheduler.scala:1848)
	at org.apache.spark.util.EventLoop.stop(EventLoop.scala:83)
	at org.apache.spark.scheduler.DAGScheduler.stop(DAGScheduler.scala:1761)
	at org.apache.spark.SparkContext$$anonfun$stop$8.apply$mcV$sp(SparkContext.scala:1931)
	at org.apache.spark.util.Utils$.tryLogNonFatalError(Utils.scala:1361)
	at org.apache.spark.SparkContext.stop(SparkContext.scala:1930)
	at org.apache.spark.SparkContext$$anonfun$2.apply$mcV$sp(SparkContext.scala:573)
	at org.apache.spark.util.SparkShutdownHook.run(ShutdownHookManager.scala:216)
	at org.apache.spark.util.SparkShutdownHookManager$$anonfun$runAll$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(ShutdownHookManager.scala:188)
	at org.apache.spark.util.SparkShutdownHookManager$$anonfun$runAll$1$$anonfun$apply$mcV$sp$1.apply(ShutdownHookManager.scala:188)
	at org.apache.spark.util.SparkShutdownHookManager$$anonfun$runAll$1$$anonfun$apply$mcV$sp$1.apply(ShutdownHookManager.scala:188)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1992)
	at org.apache.spark.util.SparkShutdownHookManager$$anonfun$runAll$1.apply$mcV$sp(ShutdownHookManager.scala:188)
	at org.apache.spark.util.SparkShutdownHookManager$$anonfun$runAll$1.apply(ShutdownHookManager.scala:188)
	at org.apache.spark.util.SparkShutdownHookManager$$anonfun$runAll$1.apply(ShutdownHookManager.scala:188)
	at scala.util.Try$.apply(Try.scala:192)
	at org.apache.spark.util.SparkShutdownHookManager.runAll(ShutdownHookManager.scala:188)
	at org.apache.spark.util.SparkShutdownHookManager$$anon$2.run(ShutdownHookManager.scala:178)
	at org.apache.hadoop.util.ShutdownHookManager$1.run(ShutdownHookManager.java:54)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:642)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2034)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2055)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2074)
	at org.apache.spark.rdd.RDD$$anonfun$take$1.apply(RDD.scala:1358)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
	at org.apache.spark.rdd.RDD.take(RDD.scala:1331)
	at org.apache.spark.rdd.RDD$$anonfun$first$1.apply(RDD.scala:1372)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
	at org.apache.spark.rdd.RDD.first(RDD.scala:1371)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.ml$dmlc$xgboost4j$scala$spark$XGBoost$$postTrackerReturnProcessing(XGBoost.scala:352)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$4.apply(XGBoost.scala:294)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$$anonfun$trainDistributed$4.apply(XGBoost.scala:256)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:285)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:255)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:200)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:48)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:118)
	at com.salesforce.op.stages.sparkwrappers.specific.OpPredictorWrapper.fit(OpPredictorWrapper.scala:99)
	at com.salesforce.op.stages.sparkwrappers.specific.OpPredictorWrapper.fit(OpPredictorWrapper.scala:67)
	at org.apache.spark.ml.Estimator.fit(Estimator.scala:61)
	at com.salesforce.op.stages.impl.tuning.OpValidator$$anonfun$9$$anonfun$10$$anonfun$apply$3.apply(OpValidator.scala:321)
	at com.salesforce.op.stages.impl.tuning.OpValidator$$anonfun$9$$anonfun$10$$anonfun$apply$3.apply(OpValidator.scala:320)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
My code is as follows:
val (response,feature) = FeatureBuilder.fromDataFrame[RealNN](frame,label)
        println(s"response = ${response}")
        val features = feature.dropWhile{case x=>x.name==id}
        println("============== opFeatures ==============")
        features.foreach(println(_))

        val transmogrifyFeature = features.transmogrify()
        val checkedFeature = response.sanityCheck(transmogrifyFeature,removeBadFeatures = true)

        val prediction = BinaryClassificationModelSelector.withTrainValidationSplit(
            modelTypesToUse = Seq(OpXGBoostClassifier)
        ).setInput(response, checkedFeature).getOutput()
        
        val evaluator = Evaluators.BinaryClassification().setLabelCol(label).setPredictionCol(prediction)
        val workflow = new OpWorkflow().setInputDataset(frame,(row: Row)=>row.get(0).toString).setResultFeatures(prediction)
        println("============training===========")
        val model = workflow.train()
        println(s"Model Summary:\n ${model.summaryPretty()}")

Thank you for reading and look forward to your reply，thanks!

**Comment by tovbinm** [comment]
@zhenchuan which TransmogrifAI version are you using?

**Comment by shenzgang** [comment]
@tovbinm Hello, I am using version 0.60

**Comment by tovbinm** [comment]
@shenzgang XGBoost fix to this issue comes with this PR - https://github.com/salesforce/TransmogrifAI/pull/402. So you can either try compiling your local version of TransmogrifAI by pulling the repo, checkout the branch `revert-399-mt/revert-spark-2.4` and then `./gradlew publishToMavenLocal`.

Or you can wait until we released the next version of TransmogrifAI. Perhaps @gerashegalov @leahmcguire can comment out when to be precise.

**Comment by shenzgang** [comment]
@tovbinm and when I use OpNaiveBayes for dichotomous cross-training, I throw the following exceptions:
Caused by: java.lang.IllegalArgumentException: requirement failed: Naive Bayes requires nonnegative feature values but found (2078,[0,1,2,3,4,6,7,8,10,11,12,13,15,21,26,30,118,460,599,1021,1022,1348,1356,1393,1948],[0.2588190451025203,-0.9659258262890684,-0.22252093395631434,0.9749279121818236,1.0,-0.861701759948068,0.5074150932938458,1205.0,4.0,6.0,33.0,76.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0]).
	at scala.Predef$.require(Predef.scala:224)
	at org.apache.spark.ml.classification.NaiveBayes$.requireNonnegativeValues(NaiveBayes.scala:232)
	at org.apache.spark.ml.classification.NaiveBayes$$anonfun$4.apply(NaiveBayes.scala:140)
	at org.apache.spark.ml.classification.NaiveBayes$$anonfun$4.apply(NaiveBayes.scala:140)
	at org.apache.spark.ml.classification.NaiveBayes$$anonfun$7.apply(NaiveBayes.scala:165)
	at org.apache.spark.ml.classification.NaiveBayes$$anonfun$7.apply(NaiveBayes.scala:163)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$aggregateByKey$1$$anonfun$apply$6.apply(PairRDDFunctions.scala:172)
	at org.apache.spark.util.collection.ExternalSorter$$anonfun$5.apply(ExternalSorter.scala:189)
	at org.apache.spark.util.collection.ExternalSorter$$anonfun$5.apply(ExternalSorter.scala:188)
	at org.apache.spark.util.collection.AppendOnlyMap.changeValue(AppendOnlyMap.scala:144)
	at org.apache.spark.util.collection.SizeTrackingAppendOnlyMap.changeValue(SizeTrackingAppendOnlyMap.scala:32)
	at org.apache.spark.util.collection.ExternalSorter.insertAll(ExternalSorter.scala:194)
	at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:63)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
	... 3 more
Some data sets have this error. Will you try other algorithms to continue training when OpNaiveBayes training fails? Or throw an exception?，
my code modelTypesToUse=Seq(OpLogisticRegression,
            OpRandomForestClassifier,
            OpGBTClassifier,
            OpLinearSVC,
            OpNaiveBayes,
            OpDecisionTreeClassifier)

**Comment by tovbinm** [comment]
I think this might have been fixed in this PR - https://github.com/salesforce/TransmogrifAI/pull/404

Try using TransmogrifAI 0.6.1 release

**Comment by shenzgang** [comment]
Ok, thanks! I'll keep following transmogrifai!

**Comment by wallwind** [comment]
@tovbinm  When does the next version of TransmogrifAI  come out

**Comment by leahmcguire** [comment]
TransmogrifAI 0.6.1 was released 2 weeks ago. Are you asking when we will release with the updated spark version?
