### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/spark/ml/classification/LinearSVCParams

### ISSUE THREAD

**Issue by spsandy101** [salesforce/TransmogrifAI#185]
**Describe the bug**
I am trying to reproduce the Titanic example from intellij idea. When I try to execute the below code, it give me the following error...
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/ml/classification/LinearSVCParams
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.salesforce.op.stages.impl.classification.BinaryClassificationModelSelector$.defaultModelsAndParams(BinaryClassificationModelSelector.scala:87)
	at com.salesforce.op.stages.impl.selector.ModelSelectorFactory$class.selector(ModelSelectorFactory.scala:73)
	at com.salesforce.op.stages.impl.classification.BinaryClassificationModelSelector$.selector(BinaryClassificationModelSelector.scala:47)
	at com.salesforce.op.stages.impl.classification.BinaryClassificationModelSelector$.withTrainValidationSplit(BinaryClassificationModelSelector.scala:195)
	at org.formcept.integration.transmogrifAITest$.main(transmogrifAITest.scala:69)
	at org.formcept.integration.transmogrifAITest.main(transmogrifAITest.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.ml.classification.LinearSVCParams
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 30 more
```
**To Reproduce**
```scala
package org.fakeOrg.FakeComponent
import com.salesforce.op._
import com.salesforce.op.evaluators.Evaluators
import com.salesforce.op.features._
import com.salesforce.op.features.FeatureBuilder
import com.salesforce.op.features.types._
import com.salesforce.op.readers.DataReaders
import com.salesforce.op.stages.impl.classification.BinaryClassificationModelsToTry.OpLogisticRegression
import com.salesforce.op.stages.impl.classification.BinaryClassificationModelSelector
import org.apache.spark.SparkConf
import org.apache.spark.sql.SparkSession
object transmogrifAITest {
  case class Passenger(id: Int, survived: Int, pClass: Option[Int], name: Option[String], sex: Option[String],
                       age: Int, sibSp: Option[Int], parCh: Option[Int], ticket: Option[String],
                       fare: Option[Double], cabin: Option[String], embarked: Option[String])
  def main(args: Array[String]): Unit = {
    implicit val spark = SparkSession.builder.config(new SparkConf()).master("local[*]").getOrCreate()
    spark.sparkContext.setLogLevel("ERROR")
    import spark.implicits._
// Define features using the OP types based on the data
    val survived = FeatureBuilder.RealNN[Passenger].extract(_.survived.toRealNN).asResponse
    val pClass = FeatureBuilder.PickList[Passenger].extract(_.pClass.map(_.toString).toPickList).asPredictor
    val name = FeatureBuilder.Text[Passenger].extract(_.name.toText).asPredictor
    val sex = FeatureBuilder.PickList[Passenger].extract(_.sex.map(_.toString).toPickList).asPredictor
    val age = FeatureBuilder.Real[Passenger].extract(_.age.toReal).asPredictor
    val sibSp = FeatureBuilder.Integral[Passenger].extract(_.sibSp.toIntegral).asPredictor
    val parCh = FeatureBuilder.Integral[Passenger].extract(_.parCh.toIntegral).asPredictor
    val ticket = FeatureBuilder.PickList[Passenger].extract(_.ticket.map(_.toString).toPickList).asPredictor
    val fare = FeatureBuilder.Real[Passenger].extract(_.fare.toReal).asPredictor
    val cabin = FeatureBuilder.PickList[Passenger].extract(_.cabin.map(_.toString).toPickList).asPredictor
    val embarked = FeatureBuilder.PickList[Passenger].extract(_.embarked.map(_.toString).toPickList).asPredictor
    // TRANSFORMED FEATURES
    // Do some basic feature engineering using knowledge of the underlying dataset
    val familySize = sibSp + parCh + 1
    val estimatedCostOfTickets = familySize * fare
    val pivotedSex = sex.pivot()
    val normedAge = age.fillMissingWithMean().zNormalize()
    val ageGroup = age.map[PickList](_.value.map(v => if (v > 18) "adult" else "child").toPickList)
    val passengerFeatures = Seq(pClass, name, age, sibSp, parCh, ticket, cabin, embarked, familySize, estimatedCostOfTickets, pivotedSex, ageGroup).transmogrify()
    // Optionally check the features with a sanity checker
    val sanityCheck = true
    val finalFeatures = if (sanityCheck) survived.sanityCheck(passengerFeatures) else passengerFeatures
    // Define the model we want to use (here a simple logistic regression) and get the resulting output
    val prediction = BinaryClassificationModelSelector.withTrainValidationSplit(modelTypesToUse = Seq(OpLogisticRegression)).setInput(survived, finalFeatures).getOutput()
    val evaluator = Evaluators.BinaryClassification().setLabelCol(survived).setPredictionCol(prediction)
    // WORKFLOW
    // Define a way to read data into our Passenger class from our CSV file
    val trainDataReader = DataReaders.Simple.csvCase[Passenger](path = Option("/**fakePath**/titanic.csv"), key = _.id.toString)
    // Define a new workflow and attach our data reader
    val workflow = new OpWorkflow().setResultFeatures(survived, prediction).setReader(trainDataReader)
    // Fit the workflow to the data
    val fittedWorkflow = workflow.train()
    println(s"Summary: ${fittedWorkflow.summary()}")
    // Manifest the result features of the workflow
    println("Scoring the model")
    val (dataframe, metrics) = fittedWorkflow.scoreAndEvaluate(evaluator = evaluator)
    println("Transformed dataframe columns:")
    dataframe.columns.foreach(println)
    println("Metrics:")
    println(metrics)
  }
}
```
My build.sbt looks like this...
```groovy
//Spark dependecies
libraryDependencies += "org.apache.spark" % "spark-core_2.11" % "2.1.0"
libraryDependencies += "org.apache.spark" % "spark-mllib_2.11" % "2.1.0"
libraryDependencies += "org.apache.spark" % "spark-sql_2.11" % "2.1.0"
libraryDependencies += "org.apache.spark" % "spark-catalyst_2.11" % "2.1.0"
libraryDependencies += "org.apache.spark" % "spark-launcher_2.11" % "2.1.0"
libraryDependencies += "org.apache.spark" % "spark-mllib_2.11" % "2.1.0"

// TransmogrifAI core dependency
resolvers += Resolver.jcenterRepo
libraryDependencies += "com.salesforce.transmogrifai" %% "transmogrifai-core" % "0.4.0"
libraryDependencies += "com.salesforce.transmogrifai" %% "transmogrifai-features" % "0.4.0"
libraryDependencies += "com.salesforce.transmogrifai" %% "transmogrifai-readers" % "0.4.0"
```
IS THERE SOMETHING THAT I AM MISSING?

**Comment by tovbinm** [comment]
Please use Spark version 2.2.1

**Comment by tovbinm** [comment]
I added a compatibility matrix here - https://github.com/salesforce/TransmogrifAI#adding-transmogrifai-into-your-project
