### ISSUE TITLE
The problem of Xgboost

### ISSUE THREAD

**Issue by jdlzy** [salesforce/TransmogrifAI#198]
Has anyone encountered this problem?When I use xgboost to train the model !

the logs is:
```

2018-12-17 19:40:16 INFO  ApplicationMaster:54 - Final app status: FAILED, exitCode: 15, (reason: User class threw exception: java.lang.RuntimeException: Key 'trackerConf' has unsupported value TrackerConf(0,scala) of type ml.dmlc.xgboost4j.scala.spark.TrackerConf
	at com.salesforce.op.utils.spark.RichMetadata$RichMap$.com$salesforce$op$utils$spark$RichMetadata$RichMap$$unsupported$1(RichMetadata.scala:207)
	at com.salesforce.op.utils.spark.RichMetadata$RichMap$$anonfun$toMetadata$extension$1.apply(RichMetadata.scala:238)
	at com.salesforce.op.utils.spark.RichMetadata$RichMap$$anonfun$toMetadata$extension$1.apply(RichMetadata.scala:218)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:221)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:428)
	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
	at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
	at com.salesforce.op.utils.spark.RichMetadata$RichMap$.toMetadata$extension(RichMetadata.scala:218)
	at com.salesforce.op.stages.impl.selector.ModelEvaluation.toMetadata(ModelSelectorSummary.scala:130)
	at com.salesforce.op.stages.impl.selector.ModelSelectorSummary$$anonfun$1.apply(ModelSelectorSummary.scala:90)
	at com.salesforce.op.stages.impl.selector.ModelSelectorSummary$$anonfun$1.apply(ModelSelectorSummary.scala:90)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.salesforce.op.stages.impl.selector.ModelSelectorSummary.toMetadata(ModelSelectorSummary.scala:90)
	at com.salesforce.op.stages.impl.selector.ModelSelector.fit(ModelSelector.scala:188)
	at com.salesforce.op.stages.impl.selector.ModelSelector.fit(ModelSelector.scala:74)
	at com.salesforce.op.utils.stages.FitStagesUtil$$anonfun$20.apply(FitStagesUtil.scala:265)
	at com.salesforce.op.utils.stages.FitStagesUtil$$anonfun$20.apply(FitStagesUtil.scala:264)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at com.salesforce.op.utils.stages.FitStagesUtil$.com$salesforce$op$utils$stages$FitStagesUtil$$fitAndTransformLayer(FitStagesUtil.scala:264)
	at com.salesforce.op.utils.stages.FitStagesUtil$$anonfun$17.apply(FitStagesUtil.scala:227)
	at com.salesforce.op.utils.stages.FitStagesUtil$$anonfun$17.apply(FitStagesUtil.scala:225)
	at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:57)
	at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:66)
	at scala.collection.mutable.ArrayOps$ofRef.foldLeft(ArrayOps.scala:186)
	at com.salesforce.op.utils.stages.FitStagesUtil$.fitAndTransformDAG(FitStagesUtil.scala:225)
	at com.salesforce.op.OpWorkflow.fitStages(OpWorkflow.scala:387)
	at com.salesforce.op.OpWorkflow.train(OpWorkflow.scala:338)
	at org.lzy.kaggle.eloRecommendation.OpElo$.trainModel(OpElo.scala:51)
	at org.lzy.kaggle.eloRecommendation.Run$.trainModel(Run.scala:61)
	at org.lzy.kaggle.eloRecommendation.Run$.main(Run.scala:29)
	at org.lzy.kaggle.eloRecommendation.Run.main(Run.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$4.run(ApplicationMaster.scala:721)
)

```

**Comment by tovbinm** [comment]
XGBoost was not yet fully tested with model selector. Looks like a bug.
