### ISSUE TITLE
Support Spark 3.0.0

### ISSUE THREAD

**Issue by koertkuipers** [salesforce/TransmogrifAI#336]
Spark 3.0.0 is actively being developed (its the current master branch for Spark).

I know its early days but i figured i start commenting here on what i ran in to so far to safe others time in the future.

My goal is to get a branch working against Spark 3.0.0 when it comes out or a Spark 3.0.0-SNAPSHOT before that. The intention is not to get this merged in: I assume Transmogrify will wait for Spark 3.0.1 before even considering that.

This builds on https://github.com/salesforce/TransmogrifAI/issues/184 and https://github.com/salesforce/TransmogrifAI/issues/332

**Comment by koertkuipers** [comment]
https://issues.apache.org/jira/browse/SPARK-26133
in spark 3 OneHotEncoderEstimator was renamed to OneHotEncoder

**Comment by koertkuipers** [comment]
Jackson has to be upgraded to 2.9.8. EitherModule was moved.
See also https://github.com/salesforce/TransmogrifAI/issues/162 and https://github.com/salesforce/TransmogrifAI/issues/173

**Comment by koertkuipers** [comment]
https://issues.apache.org/jira/browse/SPARK-26127
Spark removed a bunch of setters on regression and classification models. Since in TransmogrifAI
these are overridden this no longer compiles.

**Comment by koertkuipers** [comment]
in-house we are now using/testing transmogrifai with spark 3.0.0 snapshots. all transmogrifai tests pass. 
i did run into issues that are perhaps not covered by tests. for example BinaryClassificationModelSelector throws an error in the titanic example... probably due to some changes in the params of spark-ml models it uses that i haven't tracked down yet.

**Comment by koertkuipers** [comment]
it seems OpDefaultScalaModule is broken with jackson 2.9.9 (which is what spark 3 uses)
this took me a bit of time to track down because the error was hidden in `JsonUtils.fromString` which uses a Try/Recover that recovers from all errors masking the issue. 

anyhow this issue:
```
scala> val m = new ObjectMapper()
scala> m.registerModule(OpDefaultScalaModule)
scala> m.readValue("""{"a": "b"}""", classTag[Map[String, String]].runtimeClass)
java.lang.NullPointerException
  at com.fasterxml.jackson.databind.type.TypeBindings.<init>(TypeBindings.java:61)
  at com.fasterxml.jackson.databind.type.TypeBindings.createIfNeeded(TypeBindings.java:191)
  at com.fasterxml.jackson.databind.type.TypeFactory.constructMapLikeType(TypeFactory.java:858)
  at com.fasterxml.jackson.module.scala.deser.UnsortedMapDeserializer.<init>(OpUnsortedMapDeserializerModule.scala:66)
  at com.fasterxml.jackson.module.scala.deser.UnsortedMapDeserializerResolver$.findMapLikeDeserializer(OpUnsortedMapDeserializerModule.scala:123)
  at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._findCustomMapLikeDeserializer(BasicDeserializerFactory.java:1980)
  at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.createMapLikeDeserializer(BasicDeserializerFactory.java:1430)
  at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:386)
  at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349)
  at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
  at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
  at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
  at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:477)
  at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4190)
  at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4009)
  at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3004)
  ... 36 elided
```

**Comment by tovbinm** [comment]
Perhaps try to remove `OpDefaultScalaModule` completely (together with `OpSortedMapDeserializerModule` and `OpUnsortedMapDeserializerModule`)? 

they were added to mitigate some of the issues with older jackson library - https://github.com/salesforce/TransmogrifAI/blob/master/utils/src/main/scala/com/fasterxml/jackson/module/scala/OpDefaultScalaModule.scala#L37

**Comment by koertkuipers** [comment]
ok we have a fully working branch against spark 3.0.0-SNAPSHOT that passes all tests
it was mostly a pain because they changed the random number generator in spark 3 so all the outcomes of test are slightly different.
i plan to make this branch public once i get permission to do so.

**Comment by tovbinm** [comment]
Yay!! Thank you. Looking forward to it!
