### ISSUE TITLE
Can't load saved model into TransmogrifAI.

### ISSUE THREAD

**Issue by DineshRajanT** [salesforce/TransmogrifAI#461]
java.lang.RuntimeException: Failed to write out stage 'FeatureGeneratorStage_000000000032'
  at com.salesforce.op.stages.OpPipelineStageWriter.writeToJson(OpPipelineStageWriter.scala:81)
  at com.salesforce.op.OpWorkflowModelWriter$$anonfun$3.apply(OpWorkflowModelWriter.scala:131)

I am using Spark 2.3.3 with scala 2.11 and TransmogrifAI==0.6.1

**Comment by tovbinm** [comment]
Were you able to overcome the problem?

**Comment by DineshRajanT** [comment]
Yes...I tried the other method which is similar to the given documentation and I was able to save and load the model.
