### ISSUE TITLE
FeatureBuilder.fromDataFrame should automatically advanced types 

### ISSUE THREAD

**Issue by tovbinm** [salesforce/TransmogrifAI#64]
**Problem**
Currently `FeatureBuilder.fromDataFrame` only infers a set of primitive TransmogrifAI types directly mapped from dataframe schema, such as `Text`, `Real` etc. But more advanced types, such as `PickList`, `Email`, `Phone` etc. are not inferred, because it requires some knowledge of actual data in the dataframe.

**Solution**
Estimate value distribution for each feature and deduct a more appropriate column type. Potentially reuse logic from `CSVSchemaUtils.infer`, `SmartTextVectorizer` and `RawFeatureFilter`. 

**Alternatives**
N/A

**Comment by snabar** [comment]
This need not be automatic. Could we pass in a schema with more advanced types?

**Comment by albertodema** [comment]
Just to say that this feature is very important to lower the barrier of automl usage

**Comment by shenzgang** [comment]
@snabar Do you want to dynamically specify specific feature types? You might try to dynamically convert the type you want using the Row subscript, but there are problems with saving the model.
my test sample code：
def main(args: Array[String]): Unit = {
        if (args == null && args.length != 4){
                throw new Exception("four parameters are required Usage <database> <table> <id> <label> <index>")
        }
        val Array(database,table,label,id,pickListIndex) = args//the index of Row which you want to convert to PickList feature
        println(s"args = ${args.mkString(",")}")

        val conf = new SparkConf()
        conf.set("spark.serializer","org.apache.spark.serializer.KryoSerializer")
        implicit val session = SparkSession.builder().appName(s"${this.getClass.getSimpleName}")
                .config(conf).enableHiveSupport().master("local[*]")
                .getOrCreate()
        val frame = session.sql(s"select * from ${database}.${table}").withColumn(label,col(label).cast(DoubleType))
        frame.show(false)

        val (response,feature) = FeatureBuilder.fromDataFrame[RealNN](frame,label)
        println(s"response = ${response}")
        
        println("============== OP Features ==============")
        val realOpFeatures = ArrayBuffer[Feature[_ <: FeatureType]]()
        for (i <- 0 until(feature.size)){
                if (feature.apply(i).name != id){
                        if (i == pickListIndex.toInt){
                                val pickListFeature = FeatureBuilder.PickList[Row](feature.apply(i).name).extract(_.get(pickListIndex.toInt).toString.toPickList).asPredictor
                                realOpFeatures.append(pickListFeature)
                        }else{
                                realOpFeatures.append(feature.apply(i))
                        }
                }
        }
        realOpFeatures.foreach(println(_))
        //Auto feature engin
        val transmogrifyFeature = realOpFeatures.transmogrify()
        //Optionally check the features with a sanity checker
        val checkedFeature = response.sanityCheck(transmogrifyFeature,removeBadFeatures = true)
        //Define the model we want to use
        val prediction = BinaryClassificationModelSelector.withTrainValidationSplit(
            modelTypesToUse = Seq(OpLogisticRegression)
        ).setInput(response, checkedFeature).getOutput()
        //model evaluator
        val evaluator = Evaluators.BinaryClassification().setLabelCol(label).setPredictionCol(prediction)
        val workflow = new OpWorkflow().setInputDataset(frame,(row: Row)=>row.get(0).toString).setResultFeatures(prediction)

        val model = workflow.train()

        println(s"Model Summary:\n ${model.summaryPretty()}")
        val (scores, metrics) = model.scoreAndEvaluate(evaluator = evaluator)
        println(s"Metrics:\n ${metrics}")
        model.save("E:\\models\\model_01",true)
        session.stop()
    }
The following exception is thrown when saving the model：
Exception in thread "main" java.lang.RuntimeException: Failed to write out stage 'FeatureGeneratorStage_00000000000d'
	at com.salesforce.op.stages.OpPipelineStageWriter.writeToJson(OpPipelineStageWriter.scala:81)
	at com.salesforce.op.OpWorkflowModelWriter$$anonfun$3.apply(OpWorkflowModelWriter.scala:131)
	at com.salesforce.op.OpWorkflowModelWriter$$anonfun$3.apply(OpWorkflowModelWriter.scala:131)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at com.salesforce.op.OpWorkflowModelWriter.stagesJArray(OpWorkflowModelWriter.scala:131)
	at com.salesforce.op.OpWorkflowModelWriter.stagesJArray(OpWorkflowModelWriter.scala:108)
	at com.salesforce.op.OpWorkflowModelWriter.toJson(OpWorkflowModelWriter.scala:83)
	at com.salesforce.op.OpWorkflowModelWriter.toJsonString(OpWorkflowModelWriter.scala:68)
	at com.salesforce.op.OpWorkflowModelWriter.saveImpl(OpWorkflowModelWriter.scala:58)
	at org.apache.spark.ml.util.MLWriter.save(ReadWrite.scala:103)
	at com.salesforce.op.OpWorkflowModelWriter$.save(OpWorkflowModelWriter.scala:193)
	at com.salesforce.op.OpWorkflowModel.save(OpWorkflowModel.scala:221)
	at TestApp$.main(TestApp.scala:71)
	at TestApp.main(TestApp.scala)
Caused by: java.lang.RuntimeException: Argument 'extractFn' [TestApp$$anonfun$main$1$$anonfun$2] cannot be serialized. Make sure TestApp$$anonfun$main$1$$anonfun$2 has either no-args ctor or is an object, and does not have any external dependencies, e.g. use any out of scope variables.
	at com.salesforce.op.stages.OpPipelineStageSerializationFuns$class.serializeArgument(OpPipelineStageReaderWriter.scala:234)
	at com.salesforce.op.stages.DefaultValueReaderWriter.serializeArgument(DefaultValueReaderWriter.scala:48)
	at com.salesforce.op.stages.DefaultValueReaderWriter$$anonfun$write$1.apply(DefaultValueReaderWriter.scala:70)
	at com.salesforce.op.stages.DefaultValueReaderWriter$$anonfun$write$1.apply(DefaultValueReaderWriter.scala:69)
	at scala.util.Try$.apply(Try.scala:192)
	at com.salesforce.op.stages.DefaultValueReaderWriter.write(DefaultValueReaderWriter.scala:69)
	at com.salesforce.op.stages.FeatureGeneratorStageReaderWriter.write(FeatureGeneratorStage.scala:189)
	at com.salesforce.op.stages.FeatureGeneratorStageReaderWriter.write(FeatureGeneratorStage.scala:129)
	at com.salesforce.op.stages.OpPipelineStageWriter.writeToJson(OpPipelineStageWriter.scala:80)
	... 18 more
Caused by: java.lang.RuntimeException: Failed to create an instance of class 'TestApp$$anonfun$main$1$$anonfun$2'. Class has to either have a no-args ctor or be an object.
	at com.salesforce.op.utils.reflection.ReflectionUtils$.newInstance(ReflectionUtils.scala:106)
	at com.salesforce.op.utils.reflection.ReflectionUtils$.newInstance(ReflectionUtils.scala:87)
	at com.salesforce.op.stages.OpPipelineStageSerializationFuns$class.serializeArgument(OpPipelineStageReaderWriter.scala:231)
	... 26 more
Caused by: java.lang.NoSuchFieldException: MODULE$
	at java.lang.Class.getField(Class.java:1703)
	at com.salesforce.op.utils.reflection.ReflectionUtils$.newInstance(ReflectionUtils.scala:102)
	... 28 more
@tovbinm What's wrong with me writing this, and why is this exception thrown?

**Comment by tovbinm** [comment]
It happens due to the way we serialize stages with our models. We do not allow serializing any lambda expressions such as `.extract(_.get(pickListIndex.toInt).toString.toPickList)`, instead one has to define it as an explicit concrete class.

I recommend to rewrite your code as follows:
```scala
val (response,features) = FeatureBuilder.fromDataFrame[RealNN](frame,label)
println(s"response = ${response}")

val pickLists = features.zipWithIndex.map { 
    case (feature, i) if i == id => feature 
    case (feature, i) => feature.map(new ToPickListTransformer(i))
}
```

While `ToPickListTransformer` is top-level concrete class defined as follows:
```scala
class ToPickListTransformer(pickListIndex: Int, uid: String = UID[PickListTransformer]) extends
  UnaryTransformer[Row, PickList](operationName = "toPickList", uid = uid) {
  def transformFn: Row=> PickList= (row: Row) => row.get(pickListIndex).toString.toPickList
}
``

**Comment by shenzgang** [comment]
@tovbinm 
There may be some problems here：
uid: String = UID[PickListTransformer]) 
Error message: Cannot resolve symbol PickListTransformer
and
val realOpFeatures = features.zipWithIndex.map { 
    case (feature, i) if i == id => feature 
    case (feature, i) => feature.map(new ToPickListTransformer(i))//compile error
}
Type mismatch, expected: FeatureType => NotInferedB, actual: ToPickListTransformer

**Comment by tovbinm** [comment]
see corrected version above. thanks for pointing out the error.

**Comment by shenzgang** [comment]
@tovbinm,Thank you for your reply!but Maybe there are still some problems！
at ToPickListTransformer class
Error:(15, 9) type arguments [org.apache.spark.sql.Row,com.salesforce.op.features.types.PickList] do not conform to class UnaryTransformer's type parameter bounds [I <: com.salesforce.op.features.types.FeatureType,O <: com.salesforce.op.features.types.FeatureType]
        UnaryTransformer[Row, PickList](operationName = "toPickList", uid = uid) {
And
case (feature, i) => feature.map(f=> new ToPickListTransformer(i).setInput(f).getOutput())//complie error!

**Comment by tovbinm** [comment]
I corrected the above snippet. But it would be helpful to know what is the underlying schema in your dataset. Can you please paste the output of `frame.schema.printTreeString()`?

**Comment by shenzgang** [comment]
implicit val session = SparkSession.builder().appName(s"${this.getClass.getSimpleName}")
                .master("local[*]")
                .getOrCreate()
        val frame = session.read.option("inferSchema",true).csv(dataDir).withColumn(label,col(label).cast(DoubleType))
        frame.show(false);
        println("schema tree string:")
        frame.schema.printTreeString()
        val (response,feature) = FeatureBuilder.fromDataFrame[RealNN](frame,label)
        val features = feature.filter(x=>x.name != id)
        features.foreach(println(_))
//I want to convert the characteristics specified above!
schema tree string:
root
 |-- _c0: integer (nullable = true)
 |-- _c1: double (nullable = true)
 |-- _c2: integer (nullable = true)
 |-- _c3: string (nullable = true)
 |-- _c4: string (nullable = true)
 |-- _c5: double (nullable = true)
 |-- _c6: integer (nullable = true)
 |-- _c7: integer (nullable = true)
 |-- _c8: string (nullable = true)
 |-- _c9: double (nullable = true)
 |-- _c10: string (nullable = true)
 |-- _c11: string (nullable = true)

**Comment by shenzgang** [comment]
@tovbinm ，After I modified it according to your sample code, I still threw serialization error when saving the model!!!And I have a question:
Same procedure, same parameters and data (Titanic test data) why is the AuROC deviation obtained every time so big? Sometimes around 0.8 and sometimes above 0.9. What causes such a big difference? It feels like luck to get good metrics!

**Comment by shenzgang** [comment]
@tovbinm Hello, I have done the feature type conversion test again according to your guidance,text convert picklist , and it seems that there are still some problems when I save model:
log and error:
============== OP Features ==============
Feature(name = pClass, uid = Integral_000000000003, isResponse = false, originStage = FeatureGeneratorStage_000000000003, parents = [], distributions = [])
Feature(name = name, uid = Text_000000000004, isResponse = false, originStage = FeatureGeneratorStage_000000000004, parents = [], distributions = [])
Feature(name = sex_1-stagesApplied_PickList_00000000000d, uid = PickList_00000000000d, isResponse = false, originStage = ToPickListTransformer_00000000000d, parents = [Text_000000000005], distributions = [])
Feature(name = age, uid = Real_000000000006, isResponse = false, originStage = FeatureGeneratorStage_000000000006, parents = [], distributions = [])
Feature(name = sibSp, uid = Integral_000000000007, isResponse = false, originStage = FeatureGeneratorStage_000000000007, parents = [], distributions = [])
Feature(name = parCh, uid = Integral_000000000008, isResponse = false, originStage = FeatureGeneratorStage_000000000008, parents = [], distributions = [])
Feature(name = ticket, uid = Text_000000000009, isResponse = false, originStage = FeatureGeneratorStage_000000000009, parents = [], distributions = [])
Feature(name = fare, uid = Real_00000000000a, isResponse = false, originStage = FeatureGeneratorStage_00000000000a, parents = [], distributions = [])
Feature(name = cabin, uid = Text_00000000000b, isResponse = false, originStage = FeatureGeneratorStage_00000000000b, parents = [], distributions = [])
Feature(name = embarked, uid = Text_00000000000c, isResponse = false, originStage = FeatureGeneratorStage_00000000000c, parents = [], distributions = [])
Integer stage=================>filledValues=Feature(name = pClass-parCh-sibSp_1-stagesApplied_OPVector_00000000000e, uid = OPVector_00000000000e, isResponse = false, originStage = IntegralVectorizer_00000000000e, parents = [Integral_000000000003,Integral_000000000007,Integral_000000000008], distributions = [])
Exception in thread "main" java.lang.RuntimeException: Failed to extract value for param 'pickListIndex' for an instance of type 'source.ToPickListTransformer' due to: Scala field pickListIndex of class ToPickListTransformer isn't represented as a Java field, nor does it have a
Java accessor method. One common reason for this is that it may be a private class parameter
not used outside the primary constructor.
	at com.salesforce.op.utils.reflection.ReflectionUtils$$anonfun$com$salesforce$op$utils$reflection$ReflectionUtils$$extractParams$1.applyOrElse(ReflectionUtils.scala:388)
	at com.salesforce.op.utils.reflection.ReflectionUtils$$anonfun$com$salesforce$op$utils$reflection$ReflectionUtils$$extractParams$1.applyOrElse(ReflectionUtils.scala:387)
	at scala.collection.TraversableOnce$class.collectFirst(TraversableOnce.scala:145)
	at scala.collection.AbstractTraversable.collectFirst(Traversable.scala:104)
	at com.salesforce.op.utils.reflection.ReflectionUtils$.com$salesforce$op$utils$reflection$ReflectionUtils$$extractParams(ReflectionUtils.scala:387)
	at com.salesforce.op.utils.reflection.ReflectionUtils$$anonfun$10$$anonfun$apply$1.apply(ReflectionUtils.scala:356)
	at com.salesforce.op.utils.reflection.ReflectionUtils$$anonfun$10$$anonfun$apply$1.apply(ReflectionUtils.scala:356)
	at scala.util.Try$.apply(Try.scala:192)
	at com.salesforce.op.utils.reflection.ReflectionUtils$$anonfun$10.apply(ReflectionUtils.scala:356)
	at com.salesforce.op.utils.reflection.ReflectionUtils$$anonfun$10.apply(ReflectionUtils.scala:355)
	at scala.collection.immutable.List.map(List.scala:273)
	at com.salesforce.op.utils.reflection.ReflectionUtils$.bestCtor(ReflectionUtils.scala:355)
	at com.salesforce.op.utils.reflection.ReflectionUtils$.bestCtorWithArgs(ReflectionUtils.scala:164)
	at com.salesforce.op.OpWorkflow$$anonfun$checkCtorArgs$1$$anonfun$19.apply(OpWorkflow.scala:291)
	at com.salesforce.op.OpWorkflow$$anonfun$checkCtorArgs$1$$anonfun$19.apply(OpWorkflow.scala:291)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at com.salesforce.op.OpWorkflow$$anonfun$checkCtorArgs$1.apply$mcV$sp(OpWorkflow.scala:291)
	at com.salesforce.op.OpWorkflow$$anonfun$checkCtorArgs$1.apply(OpWorkflow.scala:289)
	at com.salesforce.op.OpWorkflow$$anonfun$checkCtorArgs$1.apply(OpWorkflow.scala:289)
	at scala.util.Try$.apply(Try.scala:192)
	at com.salesforce.op.OpWorkflow.checkCtorArgs(OpWorkflow.scala:289)
	at com.salesforce.op.OpWorkflow.checkCtorUIDs(OpWorkflow.scala:280)
	at com.salesforce.op.OpWorkflow.validateStages(OpWorkflow.scala:318)
	at com.salesforce.op.OpWorkflow.setResultFeatures(OpWorkflow.scala:91)
	at source.Demo$.main(Demo.scala:65)
	at source.Demo.main(Demo.scala)
Caused by: scala.ScalaReflectionException: Scala field pickListIndex of class ToPickListTransformer isn't represented as a Java field, nor does it have a
Java accessor method. One common reason for this is that it may be a private class parameter
not used outside the primary constructor.
	at scala.reflect.runtime.JavaMirrors$JavaMirror.scala$reflect$runtime$JavaMirrors$JavaMirror$$abort(JavaMirrors.scala:115)
	at scala.reflect.runtime.JavaMirrors$JavaMirror.scala$reflect$runtime$JavaMirrors$JavaMirror$$ErrorNonExistentField(JavaMirrors.scala:126)
	at scala.reflect.runtime.JavaMirrors$JavaMirror$JavaInstanceMirror.reflectField(JavaMirrors.scala:242)
	at scala.reflect.runtime.JavaMirrors$JavaMirror$JavaInstanceMirror.reflectField(JavaMirrors.scala:233)
	at com.salesforce.op.utils.reflection.ReflectionUtils$$anonfun$com$salesforce$op$utils$reflection$ReflectionUtils$$ctorArgs$2$1.apply(ReflectionUtils.scala:162)
	at scala.util.Try$.apply(Try.scala:192)
	at com.salesforce.op.utils.reflection.ReflectionUtils$.com$salesforce$op$utils$reflection$ReflectionUtils$$ctorArgs$2(ReflectionUtils.scala:159)
	at com.salesforce.op.utils.reflection.ReflectionUtils$$anonfun$bestCtorWithArgs$1.apply(ReflectionUtils.scala:164)
	at com.salesforce.op.utils.reflection.ReflectionUtils$$anonfun$bestCtorWithArgs$1.apply(ReflectionUtils.scala:164)
	at com.salesforce.op.utils.reflection.ReflectionUtils$$anonfun$12$$anonfun$apply$3.apply(ReflectionUtils.scala:385)
	at com.salesforce.op.utils.reflection.ReflectionUtils$$anonfun$12$$anonfun$apply$3.apply(ReflectionUtils.scala:383)
	at scala.collection.immutable.List.map(List.scala:273)
	at com.salesforce.op.utils.reflection.ReflectionUtils$$anonfun$12.apply(ReflectionUtils.scala:383)
	at com.salesforce.op.utils.reflection.ReflectionUtils$$anonfun$12.apply(ReflectionUtils.scala:382)
	at scala.collection.immutable.List.flatMap(List.scala:327)
	at com.salesforce.op.utils.reflection.ReflectionUtils$.com$salesforce$op$utils$reflection$ReflectionUtils$$extractParams(ReflectionUtils.scala:382)
	... 26 more

=======================my code is as follows==========================

implicit val spark = SparkSession.builder().appName(s"${this.getClass.getSimpleName}")
                .master("local[*]")
                .getOrCreate()
        val frame = spark.read.option("header", true).option("inferSchema", true).csv(datadir)
                .withColumn(label,col(label).cast(DoubleType))
        frame.printSchema()
        val (response,features) = FeatureBuilder.fromDataFrame[RealNN](frame, label)
        println("============== OP Features ==============")
        val array = features.tail.zipWithIndex.map {
            case (feature, 2) => {
                new ToPickListTransformer(2).setInput(feature.asInstanceOf[FeatureLike[Text]]).getOutput()
            }
            case (feature, index) => feature
        }
        array.foreach(println(_))
        val transmogrify = array.transmogrify()
        val checkedFeatures = response.sanityCheck(transmogrify,removeBadFeatures = true)
        val prediction = BinaryClassificationModelSelector.withTrainValidationSplit(
            modelTypesToUse = Seq(OpLogisticRegression)
        ).setInput(response, checkedFeatures).getOutput()
        val evaluator = Evaluators.BinaryClassification().setLabelCol(label).setPredictionCol(prediction)
        val workflow = new OpWorkflow().setInputDataset(frame,(row: Row)=>row.get(0).toString).setResultFeatures(response,prediction)
        val model = workflow.train()
        model.save("/test/model/")
        // Manifest the result features of the workflow
        println("Scoring the model")
        val (scores, metrics) = model.scoreAndEvaluate(evaluator = evaluator)
        println("Metrics:\n" + metrics)

        spark.stop()

import com.salesforce.op.features.types._
class ToPickListTransformer(pickListIndex: Int, uid: String = UID[ToPickListTransformer]) extends
        UnaryTransformer[Text, PickList](operationName = "toPickList", uid = uid) {
    override def transformFn: Text=> PickList= (v: Text) => v.value.toPickList
}

**Comment by SemanticBeeng** [comment]
Trying to think if there is something to reuse from `frameless`

https://typelevel.org/frameless/TypedEncoder.html
https://github.com/typelevel/frameless/tree/master/dataset/src/test/scala/frameless
