### ISSUE TITLE
Build failed while running titanic code

### ISSUE THREAD

**Issue by Tian-Su** [salesforce/TransmogrifAI#77]
**Describe the bug**
java.lang.ClassNotFoundException: com.salesforce.hw.OpTitanicSimple 

**To Reproduce**
./gradlew -q sparkSubmit -Dmain=com.salesforce.hw.OpTitanicSimple -Dargs="\
`pwd`/src/main/resources/TitanicDataset/TitanicPassengersTrainData.csv"

**Expected behavior**
Successful build and run through this use case with claimed result 

**Logs or screenshots**
Main class:
com.salesforce.hw.OpTitanicSimple
Arguments:
/Users/tsu001/Documents/fun_stuff/TransmogrifAI/helloworld/src/main/resources/TitanicDataset/TitanicPassengersTrainData.csv
System properties:
(spark.repl.local.jars,)
(spark.driver.memory,4G)
(SPARK_SUBMIT,true)
(spark.serializer,org.apache.spark.serializer.KryoSerializer)
(spark.app.name,op-helloworld:com.salesforce.hw.OpTitanicSimple)
(spark.jars,file:/Applications/spark-2.2.2-bin-hadoop2.7/)
(spark.submit.deployMode,client)
(spark.master,local[4])
Classpath elements:
file:/Applications/spark-2.2.2-bin-hadoop2.7/

java.lang.ClassNotFoundException: com.salesforce.hw.OpTitanicSimple
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:566)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:374)
        at org.apache.spark.util.Utils$.classForName(Utils.scala:233)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:732)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sparkSubmit'.
> Process 'command '/Applications/spark-2.2.2-bin-hadoop2.7/bin/spark-submit'' finished with non-zero exit value 101

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s

**Additional context**
This is hello world.... I can't run it through :(

**Comment by tovbinm** [comment]
Have you been following instructions from the wiki? 
Try running `./gradlew compileTestScala installDist` then run the `./gradlew sparkSubmit`

**Comment by tovbinm** [comment]
hmm, and it still failing? are you running these command from the `helloworld` folder?

**Comment by Tian-Su** [comment]
where did the wiki go?

**Comment by gokulsfdc** [comment]
@Tian-Su Please use the wiki for building titanic code at https://transmogrifai.readthedocs.io/en/latest/examples/Titanic-Binary-Classification.html
Recently wiki is moved to https://readthedocs.org/projects/transmogrifai/

**Comment by Tian-Su** [comment]
Thank you!

I previously had java 10. not knowing better things to do, I reverted to java 8. deleted this TransmogrifAI repo, recloned it, build at the main folder level and build at the helloworld level. rerun the commend, and get a different error. 

Why it is looking for titanic dataset at my spark home?
```
Using user-supplied CSV file path: 
pwd/src/main/resources/TitanicDataset/TitanicPassengersTrainData.csv
18/08/23 06:40:47 INFO OpWorkflow: Readers for types: Passenger do not have an override path in readerParams, so the default will be used
Exception in thread "main" org.apache.spark.sql.AnalysisException: Path does not exist: file:/Applications/spark-2.2.2-bin-hadoop2.7/
pwd/src/main/resources/TitanicDataset/TitanicPassengersTrainData.csv;
        at org.apache.spark.sql.execution.datasources.DataSource$.org$apache$spark$sql$execution$datasources$DataSource$$checkAndGlobPathIfNecessary(DataSource.scala:626)
        at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$14.apply(DataSource.scala:350)
        at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$14.apply(DataSource.scala:350)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
        at scala.collection.immutable.List.flatMap(List.scala:344)
        at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:349)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:178)
        at org.apache.spark.sql.DataFrameReader.csv(DataFrameReader.scala:533)
        at org.apache.spark.sql.DataFrameReader.csv(DataFrameReader.scala:412)
        at com.salesforce.op.readers.CSVProductReader.read(CSVProductReaders.scala:61)
        at com.salesforce.op.readers.DataReader$class.generateDataFrame(DataReader.scala:177)
        at com.salesforce.op.readers.CSVProductReader.generateDataFrame(CSVProductReaders.scala:49)
        at com.salesforce.op.OpWorkflow.generateRawData(OpWorkflow.scala:222)
        at com.salesforce.op.OpWorkflow.train(OpWorkflow.scala:326)
        at com.salesforce.hw.OpTitanicSimple$.main(OpTitanicSimple.scala:177)
        at com.salesforce.hw.OpTitanicSimple.main(OpTitanicSimple.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:775)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sparkSubmit'.
> Process 'command '/Applications/spark-2.2.2-bin-hadoop2.7/bin/spark-submit'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
```

**Comment by gokulsfdc** [comment]
@Tian-Su 
1. Are you running Titanic build command inside the **TransmogrifAI/helloworld** directory?
2. In the build command, the word '_pwd_' is surrounded by Acute symbol(`). Make sure that you don't strip that away.
3. Run this command, inside **TransmogrifAI/helloworld**
./gradlew -q sparkSubmit -Dmain=com.salesforce.hw.OpTitanicSimple -Dargs="\
`pwd`/src/main/resources/TitanicDataset/TitanicPassengersTrainData.csv"
4.  If you still face the issue, please send us the complete stack trace, by adding '--stacktrace' at the end of the Titanic build command.

**Comment by tovbinm** [comment]
Sounds like we can close the issue.

**Comment by volubilis** [comment]
Hello Guys it seems I am facing the same problem 

'/home/admin/spark-2.3.2-bin-hadoop2.7/bin/spark-submit'' finished with non-zero exit value 1

This is my java implementation

openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-1~deb9u1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

**Comment by tovbinm** [comment]
@volubilis you are using an incorrect Spark version. Get Spark 2.2.x - https://spark.apache.org/downloads.html
Download, unzip it and then set an environment variable: export `SPARK_HOME=<SPARK_FOLDER>`

**Comment by alexandrnikitin** [comment]
>I had to run sudo hostname -s 127.0.0.1 to get the spark driver as well. Don't fully understand why. 

@Tian-Su When you don't set a Spark master explicitly it defaults to `local[*]` and takes your hostname which isn't mapped to the loopback interface (127.0.0.1) in your case. Changing hostname could cause other things to fail. A better fix would be to add a record to `/etc/hosts` that does that. Or set the Spark master via an environment variable.

**Comment by shubamgupta** [comment]
I am getting this error. 
Exception in thread "main" java.lang.AbstractMethodError at inaryClassificationModelSelector().setInput(survived, checkedFeatures).getOutput.

I tried to create a new code using sbt also, but error still remains the same.
<img width="1440" alt="screen shot 2018-12-05 at 2 38 59 pm" src="https://user-images.githubusercontent.com/20612866/49502827-f511bd80-f89b-11e8-91e0-daa533e9f8fd.png">

**Comment by tovbinm** [comment]
@shubamgupta make sure you use the correct spark version. See this version compatibility matrix - https://github.com/salesforce/TransmogrifAI#adding-transmogrifai-into-your-project
